// Code generated by ent, DO NOT EDIT.

package runtimelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// Logger applies equality check predicate on the "logger" field. It's identical to LoggerEQ.
func Logger(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldLogger, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldMessage, v))
}

// Caller applies equality check predicate on the "caller" field. It's identical to CallerEQ.
func Caller(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldCaller, v))
}

// TraceID applies equality check predicate on the "trace_id" field. It's identical to TraceIDEQ.
func TraceID(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldTraceID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldRequestID, v))
}

// OperationName applies equality check predicate on the "operation_name" field. It's identical to OperationNameEQ.
func OperationName(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldOperationName, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldChannelID, v))
}

// ChannelName applies equality check predicate on the "channel_name" field. It's identical to ChannelNameEQ.
func ChannelName(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldChannelName, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldModelID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// LoggerEQ applies the EQ predicate on the "logger" field.
func LoggerEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldLogger, v))
}

// LoggerNEQ applies the NEQ predicate on the "logger" field.
func LoggerNEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldLogger, v))
}

// LoggerIn applies the In predicate on the "logger" field.
func LoggerIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldLogger, vs...))
}

// LoggerNotIn applies the NotIn predicate on the "logger" field.
func LoggerNotIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldLogger, vs...))
}

// LoggerGT applies the GT predicate on the "logger" field.
func LoggerGT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldLogger, v))
}

// LoggerGTE applies the GTE predicate on the "logger" field.
func LoggerGTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldLogger, v))
}

// LoggerLT applies the LT predicate on the "logger" field.
func LoggerLT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldLogger, v))
}

// LoggerLTE applies the LTE predicate on the "logger" field.
func LoggerLTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldLogger, v))
}

// LoggerContains applies the Contains predicate on the "logger" field.
func LoggerContains(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContains(FieldLogger, v))
}

// LoggerHasPrefix applies the HasPrefix predicate on the "logger" field.
func LoggerHasPrefix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasPrefix(FieldLogger, v))
}

// LoggerHasSuffix applies the HasSuffix predicate on the "logger" field.
func LoggerHasSuffix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasSuffix(FieldLogger, v))
}

// LoggerEqualFold applies the EqualFold predicate on the "logger" field.
func LoggerEqualFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEqualFold(FieldLogger, v))
}

// LoggerContainsFold applies the ContainsFold predicate on the "logger" field.
func LoggerContainsFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContainsFold(FieldLogger, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v Level) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v Level) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...Level) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...Level) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldLevel, vs...))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContainsFold(FieldMessage, v))
}

// CallerEQ applies the EQ predicate on the "caller" field.
func CallerEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldCaller, v))
}

// CallerNEQ applies the NEQ predicate on the "caller" field.
func CallerNEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldCaller, v))
}

// CallerIn applies the In predicate on the "caller" field.
func CallerIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldCaller, vs...))
}

// CallerNotIn applies the NotIn predicate on the "caller" field.
func CallerNotIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldCaller, vs...))
}

// CallerGT applies the GT predicate on the "caller" field.
func CallerGT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldCaller, v))
}

// CallerGTE applies the GTE predicate on the "caller" field.
func CallerGTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldCaller, v))
}

// CallerLT applies the LT predicate on the "caller" field.
func CallerLT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldCaller, v))
}

// CallerLTE applies the LTE predicate on the "caller" field.
func CallerLTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldCaller, v))
}

// CallerContains applies the Contains predicate on the "caller" field.
func CallerContains(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContains(FieldCaller, v))
}

// CallerHasPrefix applies the HasPrefix predicate on the "caller" field.
func CallerHasPrefix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasPrefix(FieldCaller, v))
}

// CallerHasSuffix applies the HasSuffix predicate on the "caller" field.
func CallerHasSuffix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasSuffix(FieldCaller, v))
}

// CallerIsNil applies the IsNil predicate on the "caller" field.
func CallerIsNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIsNull(FieldCaller))
}

// CallerNotNil applies the NotNil predicate on the "caller" field.
func CallerNotNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotNull(FieldCaller))
}

// CallerEqualFold applies the EqualFold predicate on the "caller" field.
func CallerEqualFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEqualFold(FieldCaller, v))
}

// CallerContainsFold applies the ContainsFold predicate on the "caller" field.
func CallerContainsFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContainsFold(FieldCaller, v))
}

// TraceIDEQ applies the EQ predicate on the "trace_id" field.
func TraceIDEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldTraceID, v))
}

// TraceIDNEQ applies the NEQ predicate on the "trace_id" field.
func TraceIDNEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldTraceID, v))
}

// TraceIDIn applies the In predicate on the "trace_id" field.
func TraceIDIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldTraceID, vs...))
}

// TraceIDNotIn applies the NotIn predicate on the "trace_id" field.
func TraceIDNotIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldTraceID, vs...))
}

// TraceIDGT applies the GT predicate on the "trace_id" field.
func TraceIDGT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldTraceID, v))
}

// TraceIDGTE applies the GTE predicate on the "trace_id" field.
func TraceIDGTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldTraceID, v))
}

// TraceIDLT applies the LT predicate on the "trace_id" field.
func TraceIDLT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldTraceID, v))
}

// TraceIDLTE applies the LTE predicate on the "trace_id" field.
func TraceIDLTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldTraceID, v))
}

// TraceIDContains applies the Contains predicate on the "trace_id" field.
func TraceIDContains(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContains(FieldTraceID, v))
}

// TraceIDHasPrefix applies the HasPrefix predicate on the "trace_id" field.
func TraceIDHasPrefix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasPrefix(FieldTraceID, v))
}

// TraceIDHasSuffix applies the HasSuffix predicate on the "trace_id" field.
func TraceIDHasSuffix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasSuffix(FieldTraceID, v))
}

// TraceIDIsNil applies the IsNil predicate on the "trace_id" field.
func TraceIDIsNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIsNull(FieldTraceID))
}

// TraceIDNotNil applies the NotNil predicate on the "trace_id" field.
func TraceIDNotNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotNull(FieldTraceID))
}

// TraceIDEqualFold applies the EqualFold predicate on the "trace_id" field.
func TraceIDEqualFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEqualFold(FieldTraceID, v))
}

// TraceIDContainsFold applies the ContainsFold predicate on the "trace_id" field.
func TraceIDContainsFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContainsFold(FieldTraceID, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContainsFold(FieldRequestID, v))
}

// OperationNameEQ applies the EQ predicate on the "operation_name" field.
func OperationNameEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldOperationName, v))
}

// OperationNameNEQ applies the NEQ predicate on the "operation_name" field.
func OperationNameNEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldOperationName, v))
}

// OperationNameIn applies the In predicate on the "operation_name" field.
func OperationNameIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldOperationName, vs...))
}

// OperationNameNotIn applies the NotIn predicate on the "operation_name" field.
func OperationNameNotIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldOperationName, vs...))
}

// OperationNameGT applies the GT predicate on the "operation_name" field.
func OperationNameGT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldOperationName, v))
}

// OperationNameGTE applies the GTE predicate on the "operation_name" field.
func OperationNameGTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldOperationName, v))
}

// OperationNameLT applies the LT predicate on the "operation_name" field.
func OperationNameLT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldOperationName, v))
}

// OperationNameLTE applies the LTE predicate on the "operation_name" field.
func OperationNameLTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldOperationName, v))
}

// OperationNameContains applies the Contains predicate on the "operation_name" field.
func OperationNameContains(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContains(FieldOperationName, v))
}

// OperationNameHasPrefix applies the HasPrefix predicate on the "operation_name" field.
func OperationNameHasPrefix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasPrefix(FieldOperationName, v))
}

// OperationNameHasSuffix applies the HasSuffix predicate on the "operation_name" field.
func OperationNameHasSuffix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasSuffix(FieldOperationName, v))
}

// OperationNameIsNil applies the IsNil predicate on the "operation_name" field.
func OperationNameIsNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIsNull(FieldOperationName))
}

// OperationNameNotNil applies the NotNil predicate on the "operation_name" field.
func OperationNameNotNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotNull(FieldOperationName))
}

// OperationNameEqualFold applies the EqualFold predicate on the "operation_name" field.
func OperationNameEqualFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEqualFold(FieldOperationName, v))
}

// OperationNameContainsFold applies the ContainsFold predicate on the "operation_name" field.
func OperationNameContainsFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContainsFold(FieldOperationName, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v int) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDIsNil applies the IsNil predicate on the "channel_id" field.
func ChannelIDIsNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIsNull(FieldChannelID))
}

// ChannelIDNotNil applies the NotNil predicate on the "channel_id" field.
func ChannelIDNotNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotNull(FieldChannelID))
}

// ChannelNameEQ applies the EQ predicate on the "channel_name" field.
func ChannelNameEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldChannelName, v))
}

// ChannelNameNEQ applies the NEQ predicate on the "channel_name" field.
func ChannelNameNEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldChannelName, v))
}

// ChannelNameIn applies the In predicate on the "channel_name" field.
func ChannelNameIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldChannelName, vs...))
}

// ChannelNameNotIn applies the NotIn predicate on the "channel_name" field.
func ChannelNameNotIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldChannelName, vs...))
}

// ChannelNameGT applies the GT predicate on the "channel_name" field.
func ChannelNameGT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldChannelName, v))
}

// ChannelNameGTE applies the GTE predicate on the "channel_name" field.
func ChannelNameGTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldChannelName, v))
}

// ChannelNameLT applies the LT predicate on the "channel_name" field.
func ChannelNameLT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldChannelName, v))
}

// ChannelNameLTE applies the LTE predicate on the "channel_name" field.
func ChannelNameLTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldChannelName, v))
}

// ChannelNameContains applies the Contains predicate on the "channel_name" field.
func ChannelNameContains(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContains(FieldChannelName, v))
}

// ChannelNameHasPrefix applies the HasPrefix predicate on the "channel_name" field.
func ChannelNameHasPrefix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasPrefix(FieldChannelName, v))
}

// ChannelNameHasSuffix applies the HasSuffix predicate on the "channel_name" field.
func ChannelNameHasSuffix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasSuffix(FieldChannelName, v))
}

// ChannelNameIsNil applies the IsNil predicate on the "channel_name" field.
func ChannelNameIsNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIsNull(FieldChannelName))
}

// ChannelNameNotNil applies the NotNil predicate on the "channel_name" field.
func ChannelNameNotNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotNull(FieldChannelName))
}

// ChannelNameEqualFold applies the EqualFold predicate on the "channel_name" field.
func ChannelNameEqualFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEqualFold(FieldChannelName, v))
}

// ChannelNameContainsFold applies the ContainsFold predicate on the "channel_name" field.
func ChannelNameContainsFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContainsFold(FieldChannelName, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDIsNil applies the IsNil predicate on the "model_id" field.
func ModelIDIsNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldIsNull(FieldModelID))
}

// ModelIDNotNil applies the NotNil predicate on the "model_id" field.
func ModelIDNotNil() predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldNotNull(FieldModelID))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.FieldContainsFold(FieldModelID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RuntimeLog) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RuntimeLog) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RuntimeLog) predicate.RuntimeLog {
	return predicate.RuntimeLog(sql.NotPredicates(p))
}
