// Code generated by ent, DO NOT EDIT.

package modelhealthsnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the modelhealthsnapshot type in the database.
	Label = "model_health_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDisplayModel holds the string denoting the display_model field in the database.
	FieldDisplayModel = "display_model"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldActualModelID holds the string denoting the actual_model_id field in the database.
	FieldActualModelID = "actual_model_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldIsHealthy holds the string denoting the is_healthy field in the database.
	FieldIsHealthy = "is_healthy"
	// FieldManualOverride holds the string denoting the manual_override field in the database.
	FieldManualOverride = "manual_override"
	// FieldProbedAt holds the string denoting the probed_at field in the database.
	FieldProbedAt = "probed_at"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// Table holds the table name of the modelhealthsnapshot in the database.
	Table = "model_health_snapshots"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "model_health_snapshots"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
)

// Columns holds all SQL columns for modelhealthsnapshot fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDisplayModel,
	FieldChannelID,
	FieldActualModelID,
	FieldSource,
	FieldIsHealthy,
	FieldManualOverride,
	FieldProbedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultIsHealthy holds the default value on creation for the "is_healthy" field.
	DefaultIsHealthy bool
	// DefaultManualOverride holds the default value on creation for the "manual_override" field.
	DefaultManualOverride bool
)

// OrderOption defines the ordering options for the ModelHealthSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDisplayModel orders the results by the display_model field.
func ByDisplayModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayModel, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByActualModelID orders the results by the actual_model_id field.
func ByActualModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualModelID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByIsHealthy orders the results by the is_healthy field.
func ByIsHealthy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsHealthy, opts...).ToFunc()
}

// ByManualOverride orders the results by the manual_override field.
func ByManualOverride(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManualOverride, opts...).ToFunc()
}

// ByProbedAt orders the results by the probed_at field.
func ByProbedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbedAt, opts...).ToFunc()
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}
