// Code generated by ent, DO NOT EDIT.

package modelhealthsnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldUpdatedAt, v))
}

// DisplayModel applies equality check predicate on the "display_model" field. It's identical to DisplayModelEQ.
func DisplayModel(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldDisplayModel, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldChannelID, v))
}

// ActualModelID applies equality check predicate on the "actual_model_id" field. It's identical to ActualModelIDEQ.
func ActualModelID(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldActualModelID, v))
}

// IsHealthy applies equality check predicate on the "is_healthy" field. It's identical to IsHealthyEQ.
func IsHealthy(v bool) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldIsHealthy, v))
}

// ManualOverride applies equality check predicate on the "manual_override" field. It's identical to ManualOverrideEQ.
func ManualOverride(v bool) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldManualOverride, v))
}

// ProbedAt applies equality check predicate on the "probed_at" field. It's identical to ProbedAtEQ.
func ProbedAt(v int64) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldProbedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLTE(FieldUpdatedAt, v))
}

// DisplayModelEQ applies the EQ predicate on the "display_model" field.
func DisplayModelEQ(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldDisplayModel, v))
}

// DisplayModelNEQ applies the NEQ predicate on the "display_model" field.
func DisplayModelNEQ(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNEQ(FieldDisplayModel, v))
}

// DisplayModelIn applies the In predicate on the "display_model" field.
func DisplayModelIn(vs ...string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldIn(FieldDisplayModel, vs...))
}

// DisplayModelNotIn applies the NotIn predicate on the "display_model" field.
func DisplayModelNotIn(vs ...string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNotIn(FieldDisplayModel, vs...))
}

// DisplayModelGT applies the GT predicate on the "display_model" field.
func DisplayModelGT(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGT(FieldDisplayModel, v))
}

// DisplayModelGTE applies the GTE predicate on the "display_model" field.
func DisplayModelGTE(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGTE(FieldDisplayModel, v))
}

// DisplayModelLT applies the LT predicate on the "display_model" field.
func DisplayModelLT(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLT(FieldDisplayModel, v))
}

// DisplayModelLTE applies the LTE predicate on the "display_model" field.
func DisplayModelLTE(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLTE(FieldDisplayModel, v))
}

// DisplayModelContains applies the Contains predicate on the "display_model" field.
func DisplayModelContains(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldContains(FieldDisplayModel, v))
}

// DisplayModelHasPrefix applies the HasPrefix predicate on the "display_model" field.
func DisplayModelHasPrefix(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldHasPrefix(FieldDisplayModel, v))
}

// DisplayModelHasSuffix applies the HasSuffix predicate on the "display_model" field.
func DisplayModelHasSuffix(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldHasSuffix(FieldDisplayModel, v))
}

// DisplayModelEqualFold applies the EqualFold predicate on the "display_model" field.
func DisplayModelEqualFold(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEqualFold(FieldDisplayModel, v))
}

// DisplayModelContainsFold applies the ContainsFold predicate on the "display_model" field.
func DisplayModelContainsFold(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldContainsFold(FieldDisplayModel, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNotIn(FieldChannelID, vs...))
}

// ActualModelIDEQ applies the EQ predicate on the "actual_model_id" field.
func ActualModelIDEQ(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldActualModelID, v))
}

// ActualModelIDNEQ applies the NEQ predicate on the "actual_model_id" field.
func ActualModelIDNEQ(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNEQ(FieldActualModelID, v))
}

// ActualModelIDIn applies the In predicate on the "actual_model_id" field.
func ActualModelIDIn(vs ...string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldIn(FieldActualModelID, vs...))
}

// ActualModelIDNotIn applies the NotIn predicate on the "actual_model_id" field.
func ActualModelIDNotIn(vs ...string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNotIn(FieldActualModelID, vs...))
}

// ActualModelIDGT applies the GT predicate on the "actual_model_id" field.
func ActualModelIDGT(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGT(FieldActualModelID, v))
}

// ActualModelIDGTE applies the GTE predicate on the "actual_model_id" field.
func ActualModelIDGTE(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGTE(FieldActualModelID, v))
}

// ActualModelIDLT applies the LT predicate on the "actual_model_id" field.
func ActualModelIDLT(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLT(FieldActualModelID, v))
}

// ActualModelIDLTE applies the LTE predicate on the "actual_model_id" field.
func ActualModelIDLTE(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLTE(FieldActualModelID, v))
}

// ActualModelIDContains applies the Contains predicate on the "actual_model_id" field.
func ActualModelIDContains(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldContains(FieldActualModelID, v))
}

// ActualModelIDHasPrefix applies the HasPrefix predicate on the "actual_model_id" field.
func ActualModelIDHasPrefix(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldHasPrefix(FieldActualModelID, v))
}

// ActualModelIDHasSuffix applies the HasSuffix predicate on the "actual_model_id" field.
func ActualModelIDHasSuffix(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldHasSuffix(FieldActualModelID, v))
}

// ActualModelIDEqualFold applies the EqualFold predicate on the "actual_model_id" field.
func ActualModelIDEqualFold(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEqualFold(FieldActualModelID, v))
}

// ActualModelIDContainsFold applies the ContainsFold predicate on the "actual_model_id" field.
func ActualModelIDContainsFold(v string) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldContainsFold(FieldActualModelID, v))
}

// IsHealthyEQ applies the EQ predicate on the "is_healthy" field.
func IsHealthyEQ(v bool) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldIsHealthy, v))
}

// IsHealthyNEQ applies the NEQ predicate on the "is_healthy" field.
func IsHealthyNEQ(v bool) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNEQ(FieldIsHealthy, v))
}

// ManualOverrideEQ applies the EQ predicate on the "manual_override" field.
func ManualOverrideEQ(v bool) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldManualOverride, v))
}

// ManualOverrideNEQ applies the NEQ predicate on the "manual_override" field.
func ManualOverrideNEQ(v bool) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNEQ(FieldManualOverride, v))
}

// ProbedAtEQ applies the EQ predicate on the "probed_at" field.
func ProbedAtEQ(v int64) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldEQ(FieldProbedAt, v))
}

// ProbedAtNEQ applies the NEQ predicate on the "probed_at" field.
func ProbedAtNEQ(v int64) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNEQ(FieldProbedAt, v))
}

// ProbedAtIn applies the In predicate on the "probed_at" field.
func ProbedAtIn(vs ...int64) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldIn(FieldProbedAt, vs...))
}

// ProbedAtNotIn applies the NotIn predicate on the "probed_at" field.
func ProbedAtNotIn(vs ...int64) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldNotIn(FieldProbedAt, vs...))
}

// ProbedAtGT applies the GT predicate on the "probed_at" field.
func ProbedAtGT(v int64) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGT(FieldProbedAt, v))
}

// ProbedAtGTE applies the GTE predicate on the "probed_at" field.
func ProbedAtGTE(v int64) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldGTE(FieldProbedAt, v))
}

// ProbedAtLT applies the LT predicate on the "probed_at" field.
func ProbedAtLT(v int64) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLT(FieldProbedAt, v))
}

// ProbedAtLTE applies the LTE predicate on the "probed_at" field.
func ProbedAtLTE(v int64) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.FieldLTE(FieldProbedAt, v))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelHealthSnapshot) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelHealthSnapshot) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelHealthSnapshot) predicate.ModelHealthSnapshot {
	return predicate.ModelHealthSnapshot(sql.NotPredicates(p))
}
