// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/modelprobeconfig"
)

// ModelProbeConfigCreate is the builder for creating a ModelProbeConfig entity.
type ModelProbeConfigCreate struct {
	config
	mutation *ModelProbeConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelProbeConfigCreate) SetCreatedAt(v time.Time) *ModelProbeConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelProbeConfigCreate) SetNillableCreatedAt(v *time.Time) *ModelProbeConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelProbeConfigCreate) SetUpdatedAt(v time.Time) *ModelProbeConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelProbeConfigCreate) SetNillableUpdatedAt(v *time.Time) *ModelProbeConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDisplayModel sets the "display_model" field.
func (_c *ModelProbeConfigCreate) SetDisplayModel(v string) *ModelProbeConfigCreate {
	_c.mutation.SetDisplayModel(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ModelProbeConfigCreate) SetChannelID(v int) *ModelProbeConfigCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetActualModelID sets the "actual_model_id" field.
func (_c *ModelProbeConfigCreate) SetActualModelID(v string) *ModelProbeConfigCreate {
	_c.mutation.SetActualModelID(v)
	return _c
}

// SetProbeEnabled sets the "probe_enabled" field.
func (_c *ModelProbeConfigCreate) SetProbeEnabled(v bool) *ModelProbeConfigCreate {
	_c.mutation.SetProbeEnabled(v)
	return _c
}

// SetNillableProbeEnabled sets the "probe_enabled" field if the given value is not nil.
func (_c *ModelProbeConfigCreate) SetNillableProbeEnabled(v *bool) *ModelProbeConfigCreate {
	if v != nil {
		_c.SetProbeEnabled(*v)
	}
	return _c
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_c *ModelProbeConfigCreate) SetConsecutiveFailures(v int) *ModelProbeConfigCreate {
	_c.mutation.SetConsecutiveFailures(v)
	return _c
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_c *ModelProbeConfigCreate) SetNillableConsecutiveFailures(v *int) *ModelProbeConfigCreate {
	if v != nil {
		_c.SetConsecutiveFailures(*v)
	}
	return _c
}

// SetAutoDisabledAt sets the "auto_disabled_at" field.
func (_c *ModelProbeConfigCreate) SetAutoDisabledAt(v int64) *ModelProbeConfigCreate {
	_c.mutation.SetAutoDisabledAt(v)
	return _c
}

// SetNillableAutoDisabledAt sets the "auto_disabled_at" field if the given value is not nil.
func (_c *ModelProbeConfigCreate) SetNillableAutoDisabledAt(v *int64) *ModelProbeConfigCreate {
	if v != nil {
		_c.SetAutoDisabledAt(*v)
	}
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ModelProbeConfigCreate) SetChannel(v *Channel) *ModelProbeConfigCreate {
	return _c.SetChannelID(v.ID)
}

// Mutation returns the ModelProbeConfigMutation object of the builder.
func (_c *ModelProbeConfigCreate) Mutation() *ModelProbeConfigMutation {
	return _c.mutation
}

// Save creates the ModelProbeConfig in the database.
func (_c *ModelProbeConfigCreate) Save(ctx context.Context) (*ModelProbeConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelProbeConfigCreate) SaveX(ctx context.Context) *ModelProbeConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelProbeConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelProbeConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelProbeConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelprobeconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelprobeconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ProbeEnabled(); !ok {
		v := modelprobeconfig.DefaultProbeEnabled
		_c.mutation.SetProbeEnabled(v)
	}
	if _, ok := _c.mutation.ConsecutiveFailures(); !ok {
		v := modelprobeconfig.DefaultConsecutiveFailures
		_c.mutation.SetConsecutiveFailures(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelProbeConfigCreate) check() error {
	if _, ok := _c.mutation.DisplayModel(); !ok {
		return &ValidationError{Name: "display_model", err: errors.New(`ent: missing required field "ModelProbeConfig.display_model"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ModelProbeConfig.channel_id"`)}
	}
	if _, ok := _c.mutation.ActualModelID(); !ok {
		return &ValidationError{Name: "actual_model_id", err: errors.New(`ent: missing required field "ModelProbeConfig.actual_model_id"`)}
	}
	if _, ok := _c.mutation.ProbeEnabled(); !ok {
		return &ValidationError{Name: "probe_enabled", err: errors.New(`ent: missing required field "ModelProbeConfig.probe_enabled"`)}
	}
	if _, ok := _c.mutation.ConsecutiveFailures(); !ok {
		return &ValidationError{Name: "consecutive_failures", err: errors.New(`ent: missing required field "ModelProbeConfig.consecutive_failures"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ModelProbeConfig.channel"`)}
	}
	return nil
}

func (_c *ModelProbeConfigCreate) sqlSave(ctx context.Context) (*ModelProbeConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelProbeConfigCreate) createSpec() (*ModelProbeConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelProbeConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelprobeconfig.Table, sqlgraph.NewFieldSpec(modelprobeconfig.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelprobeconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelprobeconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DisplayModel(); ok {
		_spec.SetField(modelprobeconfig.FieldDisplayModel, field.TypeString, value)
		_node.DisplayModel = value
	}
	if value, ok := _c.mutation.ActualModelID(); ok {
		_spec.SetField(modelprobeconfig.FieldActualModelID, field.TypeString, value)
		_node.ActualModelID = value
	}
	if value, ok := _c.mutation.ProbeEnabled(); ok {
		_spec.SetField(modelprobeconfig.FieldProbeEnabled, field.TypeBool, value)
		_node.ProbeEnabled = value
	}
	if value, ok := _c.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(modelprobeconfig.FieldConsecutiveFailures, field.TypeInt, value)
		_node.ConsecutiveFailures = value
	}
	if value, ok := _c.mutation.AutoDisabledAt(); ok {
		_spec.SetField(modelprobeconfig.FieldAutoDisabledAt, field.TypeInt64, value)
		_node.AutoDisabledAt = &value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelprobeconfig.ChannelTable,
			Columns: []string{modelprobeconfig.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelProbeConfig.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelProbeConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelProbeConfigCreate) OnConflict(opts ...sql.ConflictOption) *ModelProbeConfigUpsertOne {
	_c.conflict = opts
	return &ModelProbeConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelProbeConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelProbeConfigCreate) OnConflictColumns(columns ...string) *ModelProbeConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelProbeConfigUpsertOne{
		create: _c,
	}
}

type (
	// ModelProbeConfigUpsertOne is the builder for "upsert"-ing
	//  one ModelProbeConfig node.
	ModelProbeConfigUpsertOne struct {
		create *ModelProbeConfigCreate
	}

	// ModelProbeConfigUpsert is the "OnConflict" setter.
	ModelProbeConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelProbeConfigUpsert) SetUpdatedAt(v time.Time) *ModelProbeConfigUpsert {
	u.Set(modelprobeconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelProbeConfigUpsert) UpdateUpdatedAt() *ModelProbeConfigUpsert {
	u.SetExcluded(modelprobeconfig.FieldUpdatedAt)
	return u
}

// SetDisplayModel sets the "display_model" field.
func (u *ModelProbeConfigUpsert) SetDisplayModel(v string) *ModelProbeConfigUpsert {
	u.Set(modelprobeconfig.FieldDisplayModel, v)
	return u
}

// UpdateDisplayModel sets the "display_model" field to the value that was provided on create.
func (u *ModelProbeConfigUpsert) UpdateDisplayModel() *ModelProbeConfigUpsert {
	u.SetExcluded(modelprobeconfig.FieldDisplayModel)
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *ModelProbeConfigUpsert) SetChannelID(v int) *ModelProbeConfigUpsert {
	u.Set(modelprobeconfig.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ModelProbeConfigUpsert) UpdateChannelID() *ModelProbeConfigUpsert {
	u.SetExcluded(modelprobeconfig.FieldChannelID)
	return u
}

// SetActualModelID sets the "actual_model_id" field.
func (u *ModelProbeConfigUpsert) SetActualModelID(v string) *ModelProbeConfigUpsert {
	u.Set(modelprobeconfig.FieldActualModelID, v)
	return u
}

// UpdateActualModelID sets the "actual_model_id" field to the value that was provided on create.
func (u *ModelProbeConfigUpsert) UpdateActualModelID() *ModelProbeConfigUpsert {
	u.SetExcluded(modelprobeconfig.FieldActualModelID)
	return u
}

// SetProbeEnabled sets the "probe_enabled" field.
func (u *ModelProbeConfigUpsert) SetProbeEnabled(v bool) *ModelProbeConfigUpsert {
	u.Set(modelprobeconfig.FieldProbeEnabled, v)
	return u
}

// UpdateProbeEnabled sets the "probe_enabled" field to the value that was provided on create.
func (u *ModelProbeConfigUpsert) UpdateProbeEnabled() *ModelProbeConfigUpsert {
	u.SetExcluded(modelprobeconfig.FieldProbeEnabled)
	return u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (u *ModelProbeConfigUpsert) SetConsecutiveFailures(v int) *ModelProbeConfigUpsert {
	u.Set(modelprobeconfig.FieldConsecutiveFailures, v)
	return u
}

// UpdateConsecutiveFailures sets the "consecutive_failures" field to the value that was provided on create.
func (u *ModelProbeConfigUpsert) UpdateConsecutiveFailures() *ModelProbeConfigUpsert {
	u.SetExcluded(modelprobeconfig.FieldConsecutiveFailures)
	return u
}

// AddConsecutiveFailures adds v to the "consecutive_failures" field.
func (u *ModelProbeConfigUpsert) AddConsecutiveFailures(v int) *ModelProbeConfigUpsert {
	u.Add(modelprobeconfig.FieldConsecutiveFailures, v)
	return u
}

// SetAutoDisabledAt sets the "auto_disabled_at" field.
func (u *ModelProbeConfigUpsert) SetAutoDisabledAt(v int64) *ModelProbeConfigUpsert {
	u.Set(modelprobeconfig.FieldAutoDisabledAt, v)
	return u
}

// UpdateAutoDisabledAt sets the "auto_disabled_at" field to the value that was provided on create.
func (u *ModelProbeConfigUpsert) UpdateAutoDisabledAt() *ModelProbeConfigUpsert {
	u.SetExcluded(modelprobeconfig.FieldAutoDisabledAt)
	return u
}

// AddAutoDisabledAt adds v to the "auto_disabled_at" field.
func (u *ModelProbeConfigUpsert) AddAutoDisabledAt(v int64) *ModelProbeConfigUpsert {
	u.Add(modelprobeconfig.FieldAutoDisabledAt, v)
	return u
}

// ClearAutoDisabledAt clears the value of the "auto_disabled_at" field.
func (u *ModelProbeConfigUpsert) ClearAutoDisabledAt() *ModelProbeConfigUpsert {
	u.SetNull(modelprobeconfig.FieldAutoDisabledAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelProbeConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelProbeConfigUpsertOne) UpdateNewValues() *ModelProbeConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelprobeconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelProbeConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelProbeConfigUpsertOne) Ignore() *ModelProbeConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelProbeConfigUpsertOne) DoNothing() *ModelProbeConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelProbeConfigCreate.OnConflict
// documentation for more info.
func (u *ModelProbeConfigUpsertOne) Update(set func(*ModelProbeConfigUpsert)) *ModelProbeConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelProbeConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelProbeConfigUpsertOne) SetUpdatedAt(v time.Time) *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertOne) UpdateUpdatedAt() *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDisplayModel sets the "display_model" field.
func (u *ModelProbeConfigUpsertOne) SetDisplayModel(v string) *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetDisplayModel(v)
	})
}

// UpdateDisplayModel sets the "display_model" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertOne) UpdateDisplayModel() *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateDisplayModel()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *ModelProbeConfigUpsertOne) SetChannelID(v int) *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertOne) UpdateChannelID() *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateChannelID()
	})
}

// SetActualModelID sets the "actual_model_id" field.
func (u *ModelProbeConfigUpsertOne) SetActualModelID(v string) *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetActualModelID(v)
	})
}

// UpdateActualModelID sets the "actual_model_id" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertOne) UpdateActualModelID() *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateActualModelID()
	})
}

// SetProbeEnabled sets the "probe_enabled" field.
func (u *ModelProbeConfigUpsertOne) SetProbeEnabled(v bool) *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetProbeEnabled(v)
	})
}

// UpdateProbeEnabled sets the "probe_enabled" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertOne) UpdateProbeEnabled() *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateProbeEnabled()
	})
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (u *ModelProbeConfigUpsertOne) SetConsecutiveFailures(v int) *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetConsecutiveFailures(v)
	})
}

// AddConsecutiveFailures adds v to the "consecutive_failures" field.
func (u *ModelProbeConfigUpsertOne) AddConsecutiveFailures(v int) *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.AddConsecutiveFailures(v)
	})
}

// UpdateConsecutiveFailures sets the "consecutive_failures" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertOne) UpdateConsecutiveFailures() *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateConsecutiveFailures()
	})
}

// SetAutoDisabledAt sets the "auto_disabled_at" field.
func (u *ModelProbeConfigUpsertOne) SetAutoDisabledAt(v int64) *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetAutoDisabledAt(v)
	})
}

// AddAutoDisabledAt adds v to the "auto_disabled_at" field.
func (u *ModelProbeConfigUpsertOne) AddAutoDisabledAt(v int64) *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.AddAutoDisabledAt(v)
	})
}

// UpdateAutoDisabledAt sets the "auto_disabled_at" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertOne) UpdateAutoDisabledAt() *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateAutoDisabledAt()
	})
}

// ClearAutoDisabledAt clears the value of the "auto_disabled_at" field.
func (u *ModelProbeConfigUpsertOne) ClearAutoDisabledAt() *ModelProbeConfigUpsertOne {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.ClearAutoDisabledAt()
	})
}

// Exec executes the query.
func (u *ModelProbeConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelProbeConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelProbeConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelProbeConfigUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelProbeConfigUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelProbeConfigCreateBulk is the builder for creating many ModelProbeConfig entities in bulk.
type ModelProbeConfigCreateBulk struct {
	config
	err      error
	builders []*ModelProbeConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelProbeConfig entities in the database.
func (_c *ModelProbeConfigCreateBulk) Save(ctx context.Context) ([]*ModelProbeConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelProbeConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelProbeConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelProbeConfigCreateBulk) SaveX(ctx context.Context) []*ModelProbeConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelProbeConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelProbeConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelProbeConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelProbeConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelProbeConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelProbeConfigUpsertBulk {
	_c.conflict = opts
	return &ModelProbeConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelProbeConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelProbeConfigCreateBulk) OnConflictColumns(columns ...string) *ModelProbeConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelProbeConfigUpsertBulk{
		create: _c,
	}
}

// ModelProbeConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelProbeConfig nodes.
type ModelProbeConfigUpsertBulk struct {
	create *ModelProbeConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelProbeConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelProbeConfigUpsertBulk) UpdateNewValues() *ModelProbeConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelprobeconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelProbeConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelProbeConfigUpsertBulk) Ignore() *ModelProbeConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelProbeConfigUpsertBulk) DoNothing() *ModelProbeConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelProbeConfigCreateBulk.OnConflict
// documentation for more info.
func (u *ModelProbeConfigUpsertBulk) Update(set func(*ModelProbeConfigUpsert)) *ModelProbeConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelProbeConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelProbeConfigUpsertBulk) SetUpdatedAt(v time.Time) *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertBulk) UpdateUpdatedAt() *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDisplayModel sets the "display_model" field.
func (u *ModelProbeConfigUpsertBulk) SetDisplayModel(v string) *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetDisplayModel(v)
	})
}

// UpdateDisplayModel sets the "display_model" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertBulk) UpdateDisplayModel() *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateDisplayModel()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *ModelProbeConfigUpsertBulk) SetChannelID(v int) *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertBulk) UpdateChannelID() *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateChannelID()
	})
}

// SetActualModelID sets the "actual_model_id" field.
func (u *ModelProbeConfigUpsertBulk) SetActualModelID(v string) *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetActualModelID(v)
	})
}

// UpdateActualModelID sets the "actual_model_id" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertBulk) UpdateActualModelID() *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateActualModelID()
	})
}

// SetProbeEnabled sets the "probe_enabled" field.
func (u *ModelProbeConfigUpsertBulk) SetProbeEnabled(v bool) *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetProbeEnabled(v)
	})
}

// UpdateProbeEnabled sets the "probe_enabled" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertBulk) UpdateProbeEnabled() *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateProbeEnabled()
	})
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (u *ModelProbeConfigUpsertBulk) SetConsecutiveFailures(v int) *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetConsecutiveFailures(v)
	})
}

// AddConsecutiveFailures adds v to the "consecutive_failures" field.
func (u *ModelProbeConfigUpsertBulk) AddConsecutiveFailures(v int) *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.AddConsecutiveFailures(v)
	})
}

// UpdateConsecutiveFailures sets the "consecutive_failures" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertBulk) UpdateConsecutiveFailures() *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateConsecutiveFailures()
	})
}

// SetAutoDisabledAt sets the "auto_disabled_at" field.
func (u *ModelProbeConfigUpsertBulk) SetAutoDisabledAt(v int64) *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.SetAutoDisabledAt(v)
	})
}

// AddAutoDisabledAt adds v to the "auto_disabled_at" field.
func (u *ModelProbeConfigUpsertBulk) AddAutoDisabledAt(v int64) *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.AddAutoDisabledAt(v)
	})
}

// UpdateAutoDisabledAt sets the "auto_disabled_at" field to the value that was provided on create.
func (u *ModelProbeConfigUpsertBulk) UpdateAutoDisabledAt() *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.UpdateAutoDisabledAt()
	})
}

// ClearAutoDisabledAt clears the value of the "auto_disabled_at" field.
func (u *ModelProbeConfigUpsertBulk) ClearAutoDisabledAt() *ModelProbeConfigUpsertBulk {
	return u.Update(func(s *ModelProbeConfigUpsert) {
		s.ClearAutoDisabledAt()
	})
}

// Exec executes the query.
func (u *ModelProbeConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelProbeConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelProbeConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelProbeConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
