// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/modelprobeconfig"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ModelProbeConfigDelete is the builder for deleting a ModelProbeConfig entity.
type ModelProbeConfigDelete struct {
	config
	hooks    []Hook
	mutation *ModelProbeConfigMutation
}

// Where appends a list predicates to the ModelProbeConfigDelete builder.
func (_d *ModelProbeConfigDelete) Where(ps ...predicate.ModelProbeConfig) *ModelProbeConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModelProbeConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelProbeConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModelProbeConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelprobeconfig.Table, sqlgraph.NewFieldSpec(modelprobeconfig.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModelProbeConfigDeleteOne is the builder for deleting a single ModelProbeConfig entity.
type ModelProbeConfigDeleteOne struct {
	_d *ModelProbeConfigDelete
}

// Where appends a list predicates to the ModelProbeConfigDelete builder.
func (_d *ModelProbeConfigDeleteOne) Where(ps ...predicate.ModelProbeConfig) *ModelProbeConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModelProbeConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelprobeconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelProbeConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
