// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/modelprobeconfig"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ModelProbeConfigUpdate is the builder for updating ModelProbeConfig entities.
type ModelProbeConfigUpdate struct {
	config
	hooks     []Hook
	mutation  *ModelProbeConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ModelProbeConfigUpdate builder.
func (_u *ModelProbeConfigUpdate) Where(ps ...predicate.ModelProbeConfig) *ModelProbeConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelProbeConfigUpdate) SetUpdatedAt(v time.Time) *ModelProbeConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDisplayModel sets the "display_model" field.
func (_u *ModelProbeConfigUpdate) SetDisplayModel(v string) *ModelProbeConfigUpdate {
	_u.mutation.SetDisplayModel(v)
	return _u
}

// SetNillableDisplayModel sets the "display_model" field if the given value is not nil.
func (_u *ModelProbeConfigUpdate) SetNillableDisplayModel(v *string) *ModelProbeConfigUpdate {
	if v != nil {
		_u.SetDisplayModel(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ModelProbeConfigUpdate) SetChannelID(v int) *ModelProbeConfigUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ModelProbeConfigUpdate) SetNillableChannelID(v *int) *ModelProbeConfigUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetActualModelID sets the "actual_model_id" field.
func (_u *ModelProbeConfigUpdate) SetActualModelID(v string) *ModelProbeConfigUpdate {
	_u.mutation.SetActualModelID(v)
	return _u
}

// SetNillableActualModelID sets the "actual_model_id" field if the given value is not nil.
func (_u *ModelProbeConfigUpdate) SetNillableActualModelID(v *string) *ModelProbeConfigUpdate {
	if v != nil {
		_u.SetActualModelID(*v)
	}
	return _u
}

// SetProbeEnabled sets the "probe_enabled" field.
func (_u *ModelProbeConfigUpdate) SetProbeEnabled(v bool) *ModelProbeConfigUpdate {
	_u.mutation.SetProbeEnabled(v)
	return _u
}

// SetNillableProbeEnabled sets the "probe_enabled" field if the given value is not nil.
func (_u *ModelProbeConfigUpdate) SetNillableProbeEnabled(v *bool) *ModelProbeConfigUpdate {
	if v != nil {
		_u.SetProbeEnabled(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *ModelProbeConfigUpdate) SetConsecutiveFailures(v int) *ModelProbeConfigUpdate {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *ModelProbeConfigUpdate) SetNillableConsecutiveFailures(v *int) *ModelProbeConfigUpdate {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *ModelProbeConfigUpdate) AddConsecutiveFailures(v int) *ModelProbeConfigUpdate {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetAutoDisabledAt sets the "auto_disabled_at" field.
func (_u *ModelProbeConfigUpdate) SetAutoDisabledAt(v int64) *ModelProbeConfigUpdate {
	_u.mutation.ResetAutoDisabledAt()
	_u.mutation.SetAutoDisabledAt(v)
	return _u
}

// SetNillableAutoDisabledAt sets the "auto_disabled_at" field if the given value is not nil.
func (_u *ModelProbeConfigUpdate) SetNillableAutoDisabledAt(v *int64) *ModelProbeConfigUpdate {
	if v != nil {
		_u.SetAutoDisabledAt(*v)
	}
	return _u
}

// AddAutoDisabledAt adds value to the "auto_disabled_at" field.
func (_u *ModelProbeConfigUpdate) AddAutoDisabledAt(v int64) *ModelProbeConfigUpdate {
	_u.mutation.AddAutoDisabledAt(v)
	return _u
}

// ClearAutoDisabledAt clears the value of the "auto_disabled_at" field.
func (_u *ModelProbeConfigUpdate) ClearAutoDisabledAt() *ModelProbeConfigUpdate {
	_u.mutation.ClearAutoDisabledAt()
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ModelProbeConfigUpdate) SetChannel(v *Channel) *ModelProbeConfigUpdate {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the ModelProbeConfigMutation object of the builder.
func (_u *ModelProbeConfigUpdate) Mutation() *ModelProbeConfigMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ModelProbeConfigUpdate) ClearChannel() *ModelProbeConfigUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelProbeConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelProbeConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelProbeConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelProbeConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelProbeConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelprobeconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelProbeConfigUpdate) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelProbeConfig.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelProbeConfigUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelProbeConfigUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelProbeConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelprobeconfig.Table, modelprobeconfig.Columns, sqlgraph.NewFieldSpec(modelprobeconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelprobeconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DisplayModel(); ok {
		_spec.SetField(modelprobeconfig.FieldDisplayModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActualModelID(); ok {
		_spec.SetField(modelprobeconfig.FieldActualModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbeEnabled(); ok {
		_spec.SetField(modelprobeconfig.FieldProbeEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(modelprobeconfig.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(modelprobeconfig.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AutoDisabledAt(); ok {
		_spec.SetField(modelprobeconfig.FieldAutoDisabledAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAutoDisabledAt(); ok {
		_spec.AddField(modelprobeconfig.FieldAutoDisabledAt, field.TypeInt64, value)
	}
	if _u.mutation.AutoDisabledAtCleared() {
		_spec.ClearField(modelprobeconfig.FieldAutoDisabledAt, field.TypeInt64)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelprobeconfig.ChannelTable,
			Columns: []string{modelprobeconfig.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelprobeconfig.ChannelTable,
			Columns: []string{modelprobeconfig.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelprobeconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelProbeConfigUpdateOne is the builder for updating a single ModelProbeConfig entity.
type ModelProbeConfigUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ModelProbeConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelProbeConfigUpdateOne) SetUpdatedAt(v time.Time) *ModelProbeConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDisplayModel sets the "display_model" field.
func (_u *ModelProbeConfigUpdateOne) SetDisplayModel(v string) *ModelProbeConfigUpdateOne {
	_u.mutation.SetDisplayModel(v)
	return _u
}

// SetNillableDisplayModel sets the "display_model" field if the given value is not nil.
func (_u *ModelProbeConfigUpdateOne) SetNillableDisplayModel(v *string) *ModelProbeConfigUpdateOne {
	if v != nil {
		_u.SetDisplayModel(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ModelProbeConfigUpdateOne) SetChannelID(v int) *ModelProbeConfigUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ModelProbeConfigUpdateOne) SetNillableChannelID(v *int) *ModelProbeConfigUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetActualModelID sets the "actual_model_id" field.
func (_u *ModelProbeConfigUpdateOne) SetActualModelID(v string) *ModelProbeConfigUpdateOne {
	_u.mutation.SetActualModelID(v)
	return _u
}

// SetNillableActualModelID sets the "actual_model_id" field if the given value is not nil.
func (_u *ModelProbeConfigUpdateOne) SetNillableActualModelID(v *string) *ModelProbeConfigUpdateOne {
	if v != nil {
		_u.SetActualModelID(*v)
	}
	return _u
}

// SetProbeEnabled sets the "probe_enabled" field.
func (_u *ModelProbeConfigUpdateOne) SetProbeEnabled(v bool) *ModelProbeConfigUpdateOne {
	_u.mutation.SetProbeEnabled(v)
	return _u
}

// SetNillableProbeEnabled sets the "probe_enabled" field if the given value is not nil.
func (_u *ModelProbeConfigUpdateOne) SetNillableProbeEnabled(v *bool) *ModelProbeConfigUpdateOne {
	if v != nil {
		_u.SetProbeEnabled(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *ModelProbeConfigUpdateOne) SetConsecutiveFailures(v int) *ModelProbeConfigUpdateOne {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *ModelProbeConfigUpdateOne) SetNillableConsecutiveFailures(v *int) *ModelProbeConfigUpdateOne {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *ModelProbeConfigUpdateOne) AddConsecutiveFailures(v int) *ModelProbeConfigUpdateOne {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetAutoDisabledAt sets the "auto_disabled_at" field.
func (_u *ModelProbeConfigUpdateOne) SetAutoDisabledAt(v int64) *ModelProbeConfigUpdateOne {
	_u.mutation.ResetAutoDisabledAt()
	_u.mutation.SetAutoDisabledAt(v)
	return _u
}

// SetNillableAutoDisabledAt sets the "auto_disabled_at" field if the given value is not nil.
func (_u *ModelProbeConfigUpdateOne) SetNillableAutoDisabledAt(v *int64) *ModelProbeConfigUpdateOne {
	if v != nil {
		_u.SetAutoDisabledAt(*v)
	}
	return _u
}

// AddAutoDisabledAt adds value to the "auto_disabled_at" field.
func (_u *ModelProbeConfigUpdateOne) AddAutoDisabledAt(v int64) *ModelProbeConfigUpdateOne {
	_u.mutation.AddAutoDisabledAt(v)
	return _u
}

// ClearAutoDisabledAt clears the value of the "auto_disabled_at" field.
func (_u *ModelProbeConfigUpdateOne) ClearAutoDisabledAt() *ModelProbeConfigUpdateOne {
	_u.mutation.ClearAutoDisabledAt()
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ModelProbeConfigUpdateOne) SetChannel(v *Channel) *ModelProbeConfigUpdateOne {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the ModelProbeConfigMutation object of the builder.
func (_u *ModelProbeConfigUpdateOne) Mutation() *ModelProbeConfigMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ModelProbeConfigUpdateOne) ClearChannel() *ModelProbeConfigUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// Where appends a list predicates to the ModelProbeConfigUpdate builder.
func (_u *ModelProbeConfigUpdateOne) Where(ps ...predicate.ModelProbeConfig) *ModelProbeConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelProbeConfigUpdateOne) Select(field string, fields ...string) *ModelProbeConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelProbeConfig entity.
func (_u *ModelProbeConfigUpdateOne) Save(ctx context.Context) (*ModelProbeConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelProbeConfigUpdateOne) SaveX(ctx context.Context) *ModelProbeConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelProbeConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelProbeConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelProbeConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelprobeconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelProbeConfigUpdateOne) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelProbeConfig.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelProbeConfigUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelProbeConfigUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelProbeConfigUpdateOne) sqlSave(ctx context.Context) (_node *ModelProbeConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelprobeconfig.Table, modelprobeconfig.Columns, sqlgraph.NewFieldSpec(modelprobeconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelProbeConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelprobeconfig.FieldID)
		for _, f := range fields {
			if !modelprobeconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelprobeconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelprobeconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DisplayModel(); ok {
		_spec.SetField(modelprobeconfig.FieldDisplayModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActualModelID(); ok {
		_spec.SetField(modelprobeconfig.FieldActualModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbeEnabled(); ok {
		_spec.SetField(modelprobeconfig.FieldProbeEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(modelprobeconfig.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(modelprobeconfig.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AutoDisabledAt(); ok {
		_spec.SetField(modelprobeconfig.FieldAutoDisabledAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAutoDisabledAt(); ok {
		_spec.AddField(modelprobeconfig.FieldAutoDisabledAt, field.TypeInt64, value)
	}
	if _u.mutation.AutoDisabledAtCleared() {
		_spec.ClearField(modelprobeconfig.FieldAutoDisabledAt, field.TypeInt64)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelprobeconfig.ChannelTable,
			Columns: []string{modelprobeconfig.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelprobeconfig.ChannelTable,
			Columns: []string{modelprobeconfig.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ModelProbeConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelprobeconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
