// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/modelhealthhistory"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ModelHealthHistoryDelete is the builder for deleting a ModelHealthHistory entity.
type ModelHealthHistoryDelete struct {
	config
	hooks    []Hook
	mutation *ModelHealthHistoryMutation
}

// Where appends a list predicates to the ModelHealthHistoryDelete builder.
func (_d *ModelHealthHistoryDelete) Where(ps ...predicate.ModelHealthHistory) *ModelHealthHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModelHealthHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelHealthHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModelHealthHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelhealthhistory.Table, sqlgraph.NewFieldSpec(modelhealthhistory.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModelHealthHistoryDeleteOne is the builder for deleting a single ModelHealthHistory entity.
type ModelHealthHistoryDeleteOne struct {
	_d *ModelHealthHistoryDelete
}

// Where appends a list predicates to the ModelHealthHistoryDelete builder.
func (_d *ModelHealthHistoryDeleteOne) Where(ps ...predicate.ModelHealthHistory) *ModelHealthHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModelHealthHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelhealthhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelHealthHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
