// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/modelhealthhistory"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ModelHealthHistoryUpdate is the builder for updating ModelHealthHistory entities.
type ModelHealthHistoryUpdate struct {
	config
	hooks     []Hook
	mutation  *ModelHealthHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ModelHealthHistoryUpdate builder.
func (_u *ModelHealthHistoryUpdate) Where(ps ...predicate.ModelHealthHistory) *ModelHealthHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelHealthHistoryUpdate) SetUpdatedAt(v time.Time) *ModelHealthHistoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDisplayModel sets the "display_model" field.
func (_u *ModelHealthHistoryUpdate) SetDisplayModel(v string) *ModelHealthHistoryUpdate {
	_u.mutation.SetDisplayModel(v)
	return _u
}

// SetNillableDisplayModel sets the "display_model" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdate) SetNillableDisplayModel(v *string) *ModelHealthHistoryUpdate {
	if v != nil {
		_u.SetDisplayModel(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ModelHealthHistoryUpdate) SetChannelID(v int) *ModelHealthHistoryUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdate) SetNillableChannelID(v *int) *ModelHealthHistoryUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetActualModelID sets the "actual_model_id" field.
func (_u *ModelHealthHistoryUpdate) SetActualModelID(v string) *ModelHealthHistoryUpdate {
	_u.mutation.SetActualModelID(v)
	return _u
}

// SetNillableActualModelID sets the "actual_model_id" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdate) SetNillableActualModelID(v *string) *ModelHealthHistoryUpdate {
	if v != nil {
		_u.SetActualModelID(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ModelHealthHistoryUpdate) SetSource(v string) *ModelHealthHistoryUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdate) SetNillableSource(v *string) *ModelHealthHistoryUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIsHealthy sets the "is_healthy" field.
func (_u *ModelHealthHistoryUpdate) SetIsHealthy(v bool) *ModelHealthHistoryUpdate {
	_u.mutation.SetIsHealthy(v)
	return _u
}

// SetNillableIsHealthy sets the "is_healthy" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdate) SetNillableIsHealthy(v *bool) *ModelHealthHistoryUpdate {
	if v != nil {
		_u.SetIsHealthy(*v)
	}
	return _u
}

// SetManualOverride sets the "manual_override" field.
func (_u *ModelHealthHistoryUpdate) SetManualOverride(v bool) *ModelHealthHistoryUpdate {
	_u.mutation.SetManualOverride(v)
	return _u
}

// SetNillableManualOverride sets the "manual_override" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdate) SetNillableManualOverride(v *bool) *ModelHealthHistoryUpdate {
	if v != nil {
		_u.SetManualOverride(*v)
	}
	return _u
}

// SetProbedAt sets the "probed_at" field.
func (_u *ModelHealthHistoryUpdate) SetProbedAt(v int64) *ModelHealthHistoryUpdate {
	_u.mutation.ResetProbedAt()
	_u.mutation.SetProbedAt(v)
	return _u
}

// SetNillableProbedAt sets the "probed_at" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdate) SetNillableProbedAt(v *int64) *ModelHealthHistoryUpdate {
	if v != nil {
		_u.SetProbedAt(*v)
	}
	return _u
}

// AddProbedAt adds value to the "probed_at" field.
func (_u *ModelHealthHistoryUpdate) AddProbedAt(v int64) *ModelHealthHistoryUpdate {
	_u.mutation.AddProbedAt(v)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ModelHealthHistoryUpdate) SetChannel(v *Channel) *ModelHealthHistoryUpdate {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the ModelHealthHistoryMutation object of the builder.
func (_u *ModelHealthHistoryUpdate) Mutation() *ModelHealthHistoryMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ModelHealthHistoryUpdate) ClearChannel() *ModelHealthHistoryUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelHealthHistoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelHealthHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelHealthHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelHealthHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelHealthHistoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelhealthhistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelHealthHistoryUpdate) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelHealthHistory.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelHealthHistoryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelHealthHistoryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelHealthHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelhealthhistory.Table, modelhealthhistory.Columns, sqlgraph.NewFieldSpec(modelhealthhistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelhealthhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DisplayModel(); ok {
		_spec.SetField(modelhealthhistory.FieldDisplayModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActualModelID(); ok {
		_spec.SetField(modelhealthhistory.FieldActualModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(modelhealthhistory.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsHealthy(); ok {
		_spec.SetField(modelhealthhistory.FieldIsHealthy, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ManualOverride(); ok {
		_spec.SetField(modelhealthhistory.FieldManualOverride, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProbedAt(); ok {
		_spec.SetField(modelhealthhistory.FieldProbedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProbedAt(); ok {
		_spec.AddField(modelhealthhistory.FieldProbedAt, field.TypeInt64, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelhealthhistory.ChannelTable,
			Columns: []string{modelhealthhistory.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelhealthhistory.ChannelTable,
			Columns: []string{modelhealthhistory.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelhealthhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelHealthHistoryUpdateOne is the builder for updating a single ModelHealthHistory entity.
type ModelHealthHistoryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ModelHealthHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelHealthHistoryUpdateOne) SetUpdatedAt(v time.Time) *ModelHealthHistoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDisplayModel sets the "display_model" field.
func (_u *ModelHealthHistoryUpdateOne) SetDisplayModel(v string) *ModelHealthHistoryUpdateOne {
	_u.mutation.SetDisplayModel(v)
	return _u
}

// SetNillableDisplayModel sets the "display_model" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdateOne) SetNillableDisplayModel(v *string) *ModelHealthHistoryUpdateOne {
	if v != nil {
		_u.SetDisplayModel(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ModelHealthHistoryUpdateOne) SetChannelID(v int) *ModelHealthHistoryUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdateOne) SetNillableChannelID(v *int) *ModelHealthHistoryUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetActualModelID sets the "actual_model_id" field.
func (_u *ModelHealthHistoryUpdateOne) SetActualModelID(v string) *ModelHealthHistoryUpdateOne {
	_u.mutation.SetActualModelID(v)
	return _u
}

// SetNillableActualModelID sets the "actual_model_id" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdateOne) SetNillableActualModelID(v *string) *ModelHealthHistoryUpdateOne {
	if v != nil {
		_u.SetActualModelID(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ModelHealthHistoryUpdateOne) SetSource(v string) *ModelHealthHistoryUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdateOne) SetNillableSource(v *string) *ModelHealthHistoryUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIsHealthy sets the "is_healthy" field.
func (_u *ModelHealthHistoryUpdateOne) SetIsHealthy(v bool) *ModelHealthHistoryUpdateOne {
	_u.mutation.SetIsHealthy(v)
	return _u
}

// SetNillableIsHealthy sets the "is_healthy" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdateOne) SetNillableIsHealthy(v *bool) *ModelHealthHistoryUpdateOne {
	if v != nil {
		_u.SetIsHealthy(*v)
	}
	return _u
}

// SetManualOverride sets the "manual_override" field.
func (_u *ModelHealthHistoryUpdateOne) SetManualOverride(v bool) *ModelHealthHistoryUpdateOne {
	_u.mutation.SetManualOverride(v)
	return _u
}

// SetNillableManualOverride sets the "manual_override" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdateOne) SetNillableManualOverride(v *bool) *ModelHealthHistoryUpdateOne {
	if v != nil {
		_u.SetManualOverride(*v)
	}
	return _u
}

// SetProbedAt sets the "probed_at" field.
func (_u *ModelHealthHistoryUpdateOne) SetProbedAt(v int64) *ModelHealthHistoryUpdateOne {
	_u.mutation.ResetProbedAt()
	_u.mutation.SetProbedAt(v)
	return _u
}

// SetNillableProbedAt sets the "probed_at" field if the given value is not nil.
func (_u *ModelHealthHistoryUpdateOne) SetNillableProbedAt(v *int64) *ModelHealthHistoryUpdateOne {
	if v != nil {
		_u.SetProbedAt(*v)
	}
	return _u
}

// AddProbedAt adds value to the "probed_at" field.
func (_u *ModelHealthHistoryUpdateOne) AddProbedAt(v int64) *ModelHealthHistoryUpdateOne {
	_u.mutation.AddProbedAt(v)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ModelHealthHistoryUpdateOne) SetChannel(v *Channel) *ModelHealthHistoryUpdateOne {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the ModelHealthHistoryMutation object of the builder.
func (_u *ModelHealthHistoryUpdateOne) Mutation() *ModelHealthHistoryMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ModelHealthHistoryUpdateOne) ClearChannel() *ModelHealthHistoryUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// Where appends a list predicates to the ModelHealthHistoryUpdate builder.
func (_u *ModelHealthHistoryUpdateOne) Where(ps ...predicate.ModelHealthHistory) *ModelHealthHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelHealthHistoryUpdateOne) Select(field string, fields ...string) *ModelHealthHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelHealthHistory entity.
func (_u *ModelHealthHistoryUpdateOne) Save(ctx context.Context) (*ModelHealthHistory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelHealthHistoryUpdateOne) SaveX(ctx context.Context) *ModelHealthHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelHealthHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelHealthHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelHealthHistoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelhealthhistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelHealthHistoryUpdateOne) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelHealthHistory.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelHealthHistoryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelHealthHistoryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelHealthHistoryUpdateOne) sqlSave(ctx context.Context) (_node *ModelHealthHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelhealthhistory.Table, modelhealthhistory.Columns, sqlgraph.NewFieldSpec(modelhealthhistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelHealthHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelhealthhistory.FieldID)
		for _, f := range fields {
			if !modelhealthhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelhealthhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelhealthhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DisplayModel(); ok {
		_spec.SetField(modelhealthhistory.FieldDisplayModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActualModelID(); ok {
		_spec.SetField(modelhealthhistory.FieldActualModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(modelhealthhistory.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsHealthy(); ok {
		_spec.SetField(modelhealthhistory.FieldIsHealthy, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ManualOverride(); ok {
		_spec.SetField(modelhealthhistory.FieldManualOverride, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProbedAt(); ok {
		_spec.SetField(modelhealthhistory.FieldProbedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProbedAt(); ok {
		_spec.AddField(modelhealthhistory.FieldProbedAt, field.TypeInt64, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelhealthhistory.ChannelTable,
			Columns: []string{modelhealthhistory.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelhealthhistory.ChannelTable,
			Columns: []string{modelhealthhistory.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ModelHealthHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelhealthhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
