// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/modelhealthsnapshot"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ModelHealthSnapshotUpdate is the builder for updating ModelHealthSnapshot entities.
type ModelHealthSnapshotUpdate struct {
	config
	hooks     []Hook
	mutation  *ModelHealthSnapshotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ModelHealthSnapshotUpdate builder.
func (_u *ModelHealthSnapshotUpdate) Where(ps ...predicate.ModelHealthSnapshot) *ModelHealthSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelHealthSnapshotUpdate) SetUpdatedAt(v time.Time) *ModelHealthSnapshotUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDisplayModel sets the "display_model" field.
func (_u *ModelHealthSnapshotUpdate) SetDisplayModel(v string) *ModelHealthSnapshotUpdate {
	_u.mutation.SetDisplayModel(v)
	return _u
}

// SetNillableDisplayModel sets the "display_model" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdate) SetNillableDisplayModel(v *string) *ModelHealthSnapshotUpdate {
	if v != nil {
		_u.SetDisplayModel(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ModelHealthSnapshotUpdate) SetChannelID(v int) *ModelHealthSnapshotUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdate) SetNillableChannelID(v *int) *ModelHealthSnapshotUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetActualModelID sets the "actual_model_id" field.
func (_u *ModelHealthSnapshotUpdate) SetActualModelID(v string) *ModelHealthSnapshotUpdate {
	_u.mutation.SetActualModelID(v)
	return _u
}

// SetNillableActualModelID sets the "actual_model_id" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdate) SetNillableActualModelID(v *string) *ModelHealthSnapshotUpdate {
	if v != nil {
		_u.SetActualModelID(*v)
	}
	return _u
}

// SetIsHealthy sets the "is_healthy" field.
func (_u *ModelHealthSnapshotUpdate) SetIsHealthy(v bool) *ModelHealthSnapshotUpdate {
	_u.mutation.SetIsHealthy(v)
	return _u
}

// SetNillableIsHealthy sets the "is_healthy" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdate) SetNillableIsHealthy(v *bool) *ModelHealthSnapshotUpdate {
	if v != nil {
		_u.SetIsHealthy(*v)
	}
	return _u
}

// SetManualOverride sets the "manual_override" field.
func (_u *ModelHealthSnapshotUpdate) SetManualOverride(v bool) *ModelHealthSnapshotUpdate {
	_u.mutation.SetManualOverride(v)
	return _u
}

// SetNillableManualOverride sets the "manual_override" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdate) SetNillableManualOverride(v *bool) *ModelHealthSnapshotUpdate {
	if v != nil {
		_u.SetManualOverride(*v)
	}
	return _u
}

// SetProbedAt sets the "probed_at" field.
func (_u *ModelHealthSnapshotUpdate) SetProbedAt(v int64) *ModelHealthSnapshotUpdate {
	_u.mutation.ResetProbedAt()
	_u.mutation.SetProbedAt(v)
	return _u
}

// SetNillableProbedAt sets the "probed_at" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdate) SetNillableProbedAt(v *int64) *ModelHealthSnapshotUpdate {
	if v != nil {
		_u.SetProbedAt(*v)
	}
	return _u
}

// AddProbedAt adds value to the "probed_at" field.
func (_u *ModelHealthSnapshotUpdate) AddProbedAt(v int64) *ModelHealthSnapshotUpdate {
	_u.mutation.AddProbedAt(v)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ModelHealthSnapshotUpdate) SetChannel(v *Channel) *ModelHealthSnapshotUpdate {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the ModelHealthSnapshotMutation object of the builder.
func (_u *ModelHealthSnapshotUpdate) Mutation() *ModelHealthSnapshotMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ModelHealthSnapshotUpdate) ClearChannel() *ModelHealthSnapshotUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelHealthSnapshotUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelHealthSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelHealthSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelHealthSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelHealthSnapshotUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelhealthsnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelHealthSnapshotUpdate) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelHealthSnapshot.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelHealthSnapshotUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelHealthSnapshotUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelHealthSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelhealthsnapshot.Table, modelhealthsnapshot.Columns, sqlgraph.NewFieldSpec(modelhealthsnapshot.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelhealthsnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DisplayModel(); ok {
		_spec.SetField(modelhealthsnapshot.FieldDisplayModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActualModelID(); ok {
		_spec.SetField(modelhealthsnapshot.FieldActualModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsHealthy(); ok {
		_spec.SetField(modelhealthsnapshot.FieldIsHealthy, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ManualOverride(); ok {
		_spec.SetField(modelhealthsnapshot.FieldManualOverride, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProbedAt(); ok {
		_spec.SetField(modelhealthsnapshot.FieldProbedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProbedAt(); ok {
		_spec.AddField(modelhealthsnapshot.FieldProbedAt, field.TypeInt64, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelhealthsnapshot.ChannelTable,
			Columns: []string{modelhealthsnapshot.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelhealthsnapshot.ChannelTable,
			Columns: []string{modelhealthsnapshot.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelhealthsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelHealthSnapshotUpdateOne is the builder for updating a single ModelHealthSnapshot entity.
type ModelHealthSnapshotUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ModelHealthSnapshotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelHealthSnapshotUpdateOne) SetUpdatedAt(v time.Time) *ModelHealthSnapshotUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDisplayModel sets the "display_model" field.
func (_u *ModelHealthSnapshotUpdateOne) SetDisplayModel(v string) *ModelHealthSnapshotUpdateOne {
	_u.mutation.SetDisplayModel(v)
	return _u
}

// SetNillableDisplayModel sets the "display_model" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdateOne) SetNillableDisplayModel(v *string) *ModelHealthSnapshotUpdateOne {
	if v != nil {
		_u.SetDisplayModel(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ModelHealthSnapshotUpdateOne) SetChannelID(v int) *ModelHealthSnapshotUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdateOne) SetNillableChannelID(v *int) *ModelHealthSnapshotUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetActualModelID sets the "actual_model_id" field.
func (_u *ModelHealthSnapshotUpdateOne) SetActualModelID(v string) *ModelHealthSnapshotUpdateOne {
	_u.mutation.SetActualModelID(v)
	return _u
}

// SetNillableActualModelID sets the "actual_model_id" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdateOne) SetNillableActualModelID(v *string) *ModelHealthSnapshotUpdateOne {
	if v != nil {
		_u.SetActualModelID(*v)
	}
	return _u
}

// SetIsHealthy sets the "is_healthy" field.
func (_u *ModelHealthSnapshotUpdateOne) SetIsHealthy(v bool) *ModelHealthSnapshotUpdateOne {
	_u.mutation.SetIsHealthy(v)
	return _u
}

// SetNillableIsHealthy sets the "is_healthy" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdateOne) SetNillableIsHealthy(v *bool) *ModelHealthSnapshotUpdateOne {
	if v != nil {
		_u.SetIsHealthy(*v)
	}
	return _u
}

// SetManualOverride sets the "manual_override" field.
func (_u *ModelHealthSnapshotUpdateOne) SetManualOverride(v bool) *ModelHealthSnapshotUpdateOne {
	_u.mutation.SetManualOverride(v)
	return _u
}

// SetNillableManualOverride sets the "manual_override" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdateOne) SetNillableManualOverride(v *bool) *ModelHealthSnapshotUpdateOne {
	if v != nil {
		_u.SetManualOverride(*v)
	}
	return _u
}

// SetProbedAt sets the "probed_at" field.
func (_u *ModelHealthSnapshotUpdateOne) SetProbedAt(v int64) *ModelHealthSnapshotUpdateOne {
	_u.mutation.ResetProbedAt()
	_u.mutation.SetProbedAt(v)
	return _u
}

// SetNillableProbedAt sets the "probed_at" field if the given value is not nil.
func (_u *ModelHealthSnapshotUpdateOne) SetNillableProbedAt(v *int64) *ModelHealthSnapshotUpdateOne {
	if v != nil {
		_u.SetProbedAt(*v)
	}
	return _u
}

// AddProbedAt adds value to the "probed_at" field.
func (_u *ModelHealthSnapshotUpdateOne) AddProbedAt(v int64) *ModelHealthSnapshotUpdateOne {
	_u.mutation.AddProbedAt(v)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ModelHealthSnapshotUpdateOne) SetChannel(v *Channel) *ModelHealthSnapshotUpdateOne {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the ModelHealthSnapshotMutation object of the builder.
func (_u *ModelHealthSnapshotUpdateOne) Mutation() *ModelHealthSnapshotMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ModelHealthSnapshotUpdateOne) ClearChannel() *ModelHealthSnapshotUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// Where appends a list predicates to the ModelHealthSnapshotUpdate builder.
func (_u *ModelHealthSnapshotUpdateOne) Where(ps ...predicate.ModelHealthSnapshot) *ModelHealthSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelHealthSnapshotUpdateOne) Select(field string, fields ...string) *ModelHealthSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelHealthSnapshot entity.
func (_u *ModelHealthSnapshotUpdateOne) Save(ctx context.Context) (*ModelHealthSnapshot, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelHealthSnapshotUpdateOne) SaveX(ctx context.Context) *ModelHealthSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelHealthSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelHealthSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelHealthSnapshotUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelhealthsnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelHealthSnapshotUpdateOne) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelHealthSnapshot.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelHealthSnapshotUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelHealthSnapshotUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelHealthSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *ModelHealthSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelhealthsnapshot.Table, modelhealthsnapshot.Columns, sqlgraph.NewFieldSpec(modelhealthsnapshot.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelHealthSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelhealthsnapshot.FieldID)
		for _, f := range fields {
			if !modelhealthsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelhealthsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelhealthsnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DisplayModel(); ok {
		_spec.SetField(modelhealthsnapshot.FieldDisplayModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActualModelID(); ok {
		_spec.SetField(modelhealthsnapshot.FieldActualModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsHealthy(); ok {
		_spec.SetField(modelhealthsnapshot.FieldIsHealthy, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ManualOverride(); ok {
		_spec.SetField(modelhealthsnapshot.FieldManualOverride, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProbedAt(); ok {
		_spec.SetField(modelhealthsnapshot.FieldProbedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProbedAt(); ok {
		_spec.AddField(modelhealthsnapshot.FieldProbedAt, field.TypeInt64, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelhealthsnapshot.ChannelTable,
			Columns: []string{modelhealthsnapshot.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelhealthsnapshot.ChannelTable,
			Columns: []string{modelhealthsnapshot.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ModelHealthSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelhealthsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
