// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/modelhealthhistory"
)

// ModelHealthHistoryCreate is the builder for creating a ModelHealthHistory entity.
type ModelHealthHistoryCreate struct {
	config
	mutation *ModelHealthHistoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelHealthHistoryCreate) SetCreatedAt(v time.Time) *ModelHealthHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelHealthHistoryCreate) SetNillableCreatedAt(v *time.Time) *ModelHealthHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelHealthHistoryCreate) SetUpdatedAt(v time.Time) *ModelHealthHistoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelHealthHistoryCreate) SetNillableUpdatedAt(v *time.Time) *ModelHealthHistoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDisplayModel sets the "display_model" field.
func (_c *ModelHealthHistoryCreate) SetDisplayModel(v string) *ModelHealthHistoryCreate {
	_c.mutation.SetDisplayModel(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ModelHealthHistoryCreate) SetChannelID(v int) *ModelHealthHistoryCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetActualModelID sets the "actual_model_id" field.
func (_c *ModelHealthHistoryCreate) SetActualModelID(v string) *ModelHealthHistoryCreate {
	_c.mutation.SetActualModelID(v)
	return _c
}

// SetIsHealthy sets the "is_healthy" field.
func (_c *ModelHealthHistoryCreate) SetIsHealthy(v bool) *ModelHealthHistoryCreate {
	_c.mutation.SetIsHealthy(v)
	return _c
}

// SetNillableIsHealthy sets the "is_healthy" field if the given value is not nil.
func (_c *ModelHealthHistoryCreate) SetNillableIsHealthy(v *bool) *ModelHealthHistoryCreate {
	if v != nil {
		_c.SetIsHealthy(*v)
	}
	return _c
}

// SetManualOverride sets the "manual_override" field.
func (_c *ModelHealthHistoryCreate) SetManualOverride(v bool) *ModelHealthHistoryCreate {
	_c.mutation.SetManualOverride(v)
	return _c
}

// SetNillableManualOverride sets the "manual_override" field if the given value is not nil.
func (_c *ModelHealthHistoryCreate) SetNillableManualOverride(v *bool) *ModelHealthHistoryCreate {
	if v != nil {
		_c.SetManualOverride(*v)
	}
	return _c
}

// SetProbedAt sets the "probed_at" field.
func (_c *ModelHealthHistoryCreate) SetProbedAt(v int64) *ModelHealthHistoryCreate {
	_c.mutation.SetProbedAt(v)
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ModelHealthHistoryCreate) SetChannel(v *Channel) *ModelHealthHistoryCreate {
	return _c.SetChannelID(v.ID)
}

// Mutation returns the ModelHealthHistoryMutation object of the builder.
func (_c *ModelHealthHistoryCreate) Mutation() *ModelHealthHistoryMutation {
	return _c.mutation
}

// Save creates the ModelHealthHistory in the database.
func (_c *ModelHealthHistoryCreate) Save(ctx context.Context) (*ModelHealthHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelHealthHistoryCreate) SaveX(ctx context.Context) *ModelHealthHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelHealthHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelHealthHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelHealthHistoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelhealthhistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelhealthhistory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsHealthy(); !ok {
		v := modelhealthhistory.DefaultIsHealthy
		_c.mutation.SetIsHealthy(v)
	}
	if _, ok := _c.mutation.ManualOverride(); !ok {
		v := modelhealthhistory.DefaultManualOverride
		_c.mutation.SetManualOverride(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelHealthHistoryCreate) check() error {
	if _, ok := _c.mutation.DisplayModel(); !ok {
		return &ValidationError{Name: "display_model", err: errors.New(`ent: missing required field "ModelHealthHistory.display_model"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ModelHealthHistory.channel_id"`)}
	}
	if _, ok := _c.mutation.ActualModelID(); !ok {
		return &ValidationError{Name: "actual_model_id", err: errors.New(`ent: missing required field "ModelHealthHistory.actual_model_id"`)}
	}
	if _, ok := _c.mutation.IsHealthy(); !ok {
		return &ValidationError{Name: "is_healthy", err: errors.New(`ent: missing required field "ModelHealthHistory.is_healthy"`)}
	}
	if _, ok := _c.mutation.ManualOverride(); !ok {
		return &ValidationError{Name: "manual_override", err: errors.New(`ent: missing required field "ModelHealthHistory.manual_override"`)}
	}
	if _, ok := _c.mutation.ProbedAt(); !ok {
		return &ValidationError{Name: "probed_at", err: errors.New(`ent: missing required field "ModelHealthHistory.probed_at"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ModelHealthHistory.channel"`)}
	}
	return nil
}

func (_c *ModelHealthHistoryCreate) sqlSave(ctx context.Context) (*ModelHealthHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelHealthHistoryCreate) createSpec() (*ModelHealthHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelHealthHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelhealthhistory.Table, sqlgraph.NewFieldSpec(modelhealthhistory.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelhealthhistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelhealthhistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DisplayModel(); ok {
		_spec.SetField(modelhealthhistory.FieldDisplayModel, field.TypeString, value)
		_node.DisplayModel = value
	}
	if value, ok := _c.mutation.ActualModelID(); ok {
		_spec.SetField(modelhealthhistory.FieldActualModelID, field.TypeString, value)
		_node.ActualModelID = value
	}
	if value, ok := _c.mutation.IsHealthy(); ok {
		_spec.SetField(modelhealthhistory.FieldIsHealthy, field.TypeBool, value)
		_node.IsHealthy = value
	}
	if value, ok := _c.mutation.ManualOverride(); ok {
		_spec.SetField(modelhealthhistory.FieldManualOverride, field.TypeBool, value)
		_node.ManualOverride = value
	}
	if value, ok := _c.mutation.ProbedAt(); ok {
		_spec.SetField(modelhealthhistory.FieldProbedAt, field.TypeInt64, value)
		_node.ProbedAt = value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelhealthhistory.ChannelTable,
			Columns: []string{modelhealthhistory.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelHealthHistory.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelHealthHistoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelHealthHistoryCreate) OnConflict(opts ...sql.ConflictOption) *ModelHealthHistoryUpsertOne {
	_c.conflict = opts
	return &ModelHealthHistoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelHealthHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelHealthHistoryCreate) OnConflictColumns(columns ...string) *ModelHealthHistoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelHealthHistoryUpsertOne{
		create: _c,
	}
}

type (
	// ModelHealthHistoryUpsertOne is the builder for "upsert"-ing
	//  one ModelHealthHistory node.
	ModelHealthHistoryUpsertOne struct {
		create *ModelHealthHistoryCreate
	}

	// ModelHealthHistoryUpsert is the "OnConflict" setter.
	ModelHealthHistoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelHealthHistoryUpsert) SetUpdatedAt(v time.Time) *ModelHealthHistoryUpsert {
	u.Set(modelhealthhistory.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsert) UpdateUpdatedAt() *ModelHealthHistoryUpsert {
	u.SetExcluded(modelhealthhistory.FieldUpdatedAt)
	return u
}

// SetDisplayModel sets the "display_model" field.
func (u *ModelHealthHistoryUpsert) SetDisplayModel(v string) *ModelHealthHistoryUpsert {
	u.Set(modelhealthhistory.FieldDisplayModel, v)
	return u
}

// UpdateDisplayModel sets the "display_model" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsert) UpdateDisplayModel() *ModelHealthHistoryUpsert {
	u.SetExcluded(modelhealthhistory.FieldDisplayModel)
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *ModelHealthHistoryUpsert) SetChannelID(v int) *ModelHealthHistoryUpsert {
	u.Set(modelhealthhistory.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsert) UpdateChannelID() *ModelHealthHistoryUpsert {
	u.SetExcluded(modelhealthhistory.FieldChannelID)
	return u
}

// SetActualModelID sets the "actual_model_id" field.
func (u *ModelHealthHistoryUpsert) SetActualModelID(v string) *ModelHealthHistoryUpsert {
	u.Set(modelhealthhistory.FieldActualModelID, v)
	return u
}

// UpdateActualModelID sets the "actual_model_id" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsert) UpdateActualModelID() *ModelHealthHistoryUpsert {
	u.SetExcluded(modelhealthhistory.FieldActualModelID)
	return u
}

// SetIsHealthy sets the "is_healthy" field.
func (u *ModelHealthHistoryUpsert) SetIsHealthy(v bool) *ModelHealthHistoryUpsert {
	u.Set(modelhealthhistory.FieldIsHealthy, v)
	return u
}

// UpdateIsHealthy sets the "is_healthy" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsert) UpdateIsHealthy() *ModelHealthHistoryUpsert {
	u.SetExcluded(modelhealthhistory.FieldIsHealthy)
	return u
}

// SetManualOverride sets the "manual_override" field.
func (u *ModelHealthHistoryUpsert) SetManualOverride(v bool) *ModelHealthHistoryUpsert {
	u.Set(modelhealthhistory.FieldManualOverride, v)
	return u
}

// UpdateManualOverride sets the "manual_override" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsert) UpdateManualOverride() *ModelHealthHistoryUpsert {
	u.SetExcluded(modelhealthhistory.FieldManualOverride)
	return u
}

// SetProbedAt sets the "probed_at" field.
func (u *ModelHealthHistoryUpsert) SetProbedAt(v int64) *ModelHealthHistoryUpsert {
	u.Set(modelhealthhistory.FieldProbedAt, v)
	return u
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsert) UpdateProbedAt() *ModelHealthHistoryUpsert {
	u.SetExcluded(modelhealthhistory.FieldProbedAt)
	return u
}

// AddProbedAt adds v to the "probed_at" field.
func (u *ModelHealthHistoryUpsert) AddProbedAt(v int64) *ModelHealthHistoryUpsert {
	u.Add(modelhealthhistory.FieldProbedAt, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelHealthHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelHealthHistoryUpsertOne) UpdateNewValues() *ModelHealthHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelhealthhistory.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelHealthHistory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelHealthHistoryUpsertOne) Ignore() *ModelHealthHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelHealthHistoryUpsertOne) DoNothing() *ModelHealthHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelHealthHistoryCreate.OnConflict
// documentation for more info.
func (u *ModelHealthHistoryUpsertOne) Update(set func(*ModelHealthHistoryUpsert)) *ModelHealthHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelHealthHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelHealthHistoryUpsertOne) SetUpdatedAt(v time.Time) *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertOne) UpdateUpdatedAt() *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDisplayModel sets the "display_model" field.
func (u *ModelHealthHistoryUpsertOne) SetDisplayModel(v string) *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetDisplayModel(v)
	})
}

// UpdateDisplayModel sets the "display_model" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertOne) UpdateDisplayModel() *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateDisplayModel()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *ModelHealthHistoryUpsertOne) SetChannelID(v int) *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertOne) UpdateChannelID() *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateChannelID()
	})
}

// SetActualModelID sets the "actual_model_id" field.
func (u *ModelHealthHistoryUpsertOne) SetActualModelID(v string) *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetActualModelID(v)
	})
}

// UpdateActualModelID sets the "actual_model_id" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertOne) UpdateActualModelID() *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateActualModelID()
	})
}

// SetIsHealthy sets the "is_healthy" field.
func (u *ModelHealthHistoryUpsertOne) SetIsHealthy(v bool) *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetIsHealthy(v)
	})
}

// UpdateIsHealthy sets the "is_healthy" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertOne) UpdateIsHealthy() *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateIsHealthy()
	})
}

// SetManualOverride sets the "manual_override" field.
func (u *ModelHealthHistoryUpsertOne) SetManualOverride(v bool) *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetManualOverride(v)
	})
}

// UpdateManualOverride sets the "manual_override" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertOne) UpdateManualOverride() *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateManualOverride()
	})
}

// SetProbedAt sets the "probed_at" field.
func (u *ModelHealthHistoryUpsertOne) SetProbedAt(v int64) *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetProbedAt(v)
	})
}

// AddProbedAt adds v to the "probed_at" field.
func (u *ModelHealthHistoryUpsertOne) AddProbedAt(v int64) *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.AddProbedAt(v)
	})
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertOne) UpdateProbedAt() *ModelHealthHistoryUpsertOne {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateProbedAt()
	})
}

// Exec executes the query.
func (u *ModelHealthHistoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelHealthHistoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelHealthHistoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelHealthHistoryUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelHealthHistoryUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelHealthHistoryCreateBulk is the builder for creating many ModelHealthHistory entities in bulk.
type ModelHealthHistoryCreateBulk struct {
	config
	err      error
	builders []*ModelHealthHistoryCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelHealthHistory entities in the database.
func (_c *ModelHealthHistoryCreateBulk) Save(ctx context.Context) ([]*ModelHealthHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelHealthHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelHealthHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelHealthHistoryCreateBulk) SaveX(ctx context.Context) []*ModelHealthHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelHealthHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelHealthHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelHealthHistory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelHealthHistoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelHealthHistoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelHealthHistoryUpsertBulk {
	_c.conflict = opts
	return &ModelHealthHistoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelHealthHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelHealthHistoryCreateBulk) OnConflictColumns(columns ...string) *ModelHealthHistoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelHealthHistoryUpsertBulk{
		create: _c,
	}
}

// ModelHealthHistoryUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelHealthHistory nodes.
type ModelHealthHistoryUpsertBulk struct {
	create *ModelHealthHistoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelHealthHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelHealthHistoryUpsertBulk) UpdateNewValues() *ModelHealthHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelhealthhistory.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelHealthHistory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelHealthHistoryUpsertBulk) Ignore() *ModelHealthHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelHealthHistoryUpsertBulk) DoNothing() *ModelHealthHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelHealthHistoryCreateBulk.OnConflict
// documentation for more info.
func (u *ModelHealthHistoryUpsertBulk) Update(set func(*ModelHealthHistoryUpsert)) *ModelHealthHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelHealthHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelHealthHistoryUpsertBulk) SetUpdatedAt(v time.Time) *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertBulk) UpdateUpdatedAt() *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDisplayModel sets the "display_model" field.
func (u *ModelHealthHistoryUpsertBulk) SetDisplayModel(v string) *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetDisplayModel(v)
	})
}

// UpdateDisplayModel sets the "display_model" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertBulk) UpdateDisplayModel() *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateDisplayModel()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *ModelHealthHistoryUpsertBulk) SetChannelID(v int) *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertBulk) UpdateChannelID() *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateChannelID()
	})
}

// SetActualModelID sets the "actual_model_id" field.
func (u *ModelHealthHistoryUpsertBulk) SetActualModelID(v string) *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetActualModelID(v)
	})
}

// UpdateActualModelID sets the "actual_model_id" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertBulk) UpdateActualModelID() *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateActualModelID()
	})
}

// SetIsHealthy sets the "is_healthy" field.
func (u *ModelHealthHistoryUpsertBulk) SetIsHealthy(v bool) *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetIsHealthy(v)
	})
}

// UpdateIsHealthy sets the "is_healthy" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertBulk) UpdateIsHealthy() *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateIsHealthy()
	})
}

// SetManualOverride sets the "manual_override" field.
func (u *ModelHealthHistoryUpsertBulk) SetManualOverride(v bool) *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetManualOverride(v)
	})
}

// UpdateManualOverride sets the "manual_override" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertBulk) UpdateManualOverride() *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateManualOverride()
	})
}

// SetProbedAt sets the "probed_at" field.
func (u *ModelHealthHistoryUpsertBulk) SetProbedAt(v int64) *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.SetProbedAt(v)
	})
}

// AddProbedAt adds v to the "probed_at" field.
func (u *ModelHealthHistoryUpsertBulk) AddProbedAt(v int64) *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.AddProbedAt(v)
	})
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *ModelHealthHistoryUpsertBulk) UpdateProbedAt() *ModelHealthHistoryUpsertBulk {
	return u.Update(func(s *ModelHealthHistoryUpsert) {
		s.UpdateProbedAt()
	})
}

// Exec executes the query.
func (u *ModelHealthHistoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelHealthHistoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelHealthHistoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelHealthHistoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
