// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/modelhealthsnapshot"
)

// ModelHealthSnapshotCreate is the builder for creating a ModelHealthSnapshot entity.
type ModelHealthSnapshotCreate struct {
	config
	mutation *ModelHealthSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelHealthSnapshotCreate) SetCreatedAt(v time.Time) *ModelHealthSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelHealthSnapshotCreate) SetNillableCreatedAt(v *time.Time) *ModelHealthSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelHealthSnapshotCreate) SetUpdatedAt(v time.Time) *ModelHealthSnapshotCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelHealthSnapshotCreate) SetNillableUpdatedAt(v *time.Time) *ModelHealthSnapshotCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDisplayModel sets the "display_model" field.
func (_c *ModelHealthSnapshotCreate) SetDisplayModel(v string) *ModelHealthSnapshotCreate {
	_c.mutation.SetDisplayModel(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ModelHealthSnapshotCreate) SetChannelID(v int) *ModelHealthSnapshotCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetActualModelID sets the "actual_model_id" field.
func (_c *ModelHealthSnapshotCreate) SetActualModelID(v string) *ModelHealthSnapshotCreate {
	_c.mutation.SetActualModelID(v)
	return _c
}

// SetIsHealthy sets the "is_healthy" field.
func (_c *ModelHealthSnapshotCreate) SetIsHealthy(v bool) *ModelHealthSnapshotCreate {
	_c.mutation.SetIsHealthy(v)
	return _c
}

// SetNillableIsHealthy sets the "is_healthy" field if the given value is not nil.
func (_c *ModelHealthSnapshotCreate) SetNillableIsHealthy(v *bool) *ModelHealthSnapshotCreate {
	if v != nil {
		_c.SetIsHealthy(*v)
	}
	return _c
}

// SetManualOverride sets the "manual_override" field.
func (_c *ModelHealthSnapshotCreate) SetManualOverride(v bool) *ModelHealthSnapshotCreate {
	_c.mutation.SetManualOverride(v)
	return _c
}

// SetNillableManualOverride sets the "manual_override" field if the given value is not nil.
func (_c *ModelHealthSnapshotCreate) SetNillableManualOverride(v *bool) *ModelHealthSnapshotCreate {
	if v != nil {
		_c.SetManualOverride(*v)
	}
	return _c
}

// SetProbedAt sets the "probed_at" field.
func (_c *ModelHealthSnapshotCreate) SetProbedAt(v int64) *ModelHealthSnapshotCreate {
	_c.mutation.SetProbedAt(v)
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ModelHealthSnapshotCreate) SetChannel(v *Channel) *ModelHealthSnapshotCreate {
	return _c.SetChannelID(v.ID)
}

// Mutation returns the ModelHealthSnapshotMutation object of the builder.
func (_c *ModelHealthSnapshotCreate) Mutation() *ModelHealthSnapshotMutation {
	return _c.mutation
}

// Save creates the ModelHealthSnapshot in the database.
func (_c *ModelHealthSnapshotCreate) Save(ctx context.Context) (*ModelHealthSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelHealthSnapshotCreate) SaveX(ctx context.Context) *ModelHealthSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelHealthSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelHealthSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelHealthSnapshotCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelhealthsnapshot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelhealthsnapshot.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsHealthy(); !ok {
		v := modelhealthsnapshot.DefaultIsHealthy
		_c.mutation.SetIsHealthy(v)
	}
	if _, ok := _c.mutation.ManualOverride(); !ok {
		v := modelhealthsnapshot.DefaultManualOverride
		_c.mutation.SetManualOverride(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelHealthSnapshotCreate) check() error {
	if _, ok := _c.mutation.DisplayModel(); !ok {
		return &ValidationError{Name: "display_model", err: errors.New(`ent: missing required field "ModelHealthSnapshot.display_model"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ModelHealthSnapshot.channel_id"`)}
	}
	if _, ok := _c.mutation.ActualModelID(); !ok {
		return &ValidationError{Name: "actual_model_id", err: errors.New(`ent: missing required field "ModelHealthSnapshot.actual_model_id"`)}
	}
	if _, ok := _c.mutation.IsHealthy(); !ok {
		return &ValidationError{Name: "is_healthy", err: errors.New(`ent: missing required field "ModelHealthSnapshot.is_healthy"`)}
	}
	if _, ok := _c.mutation.ManualOverride(); !ok {
		return &ValidationError{Name: "manual_override", err: errors.New(`ent: missing required field "ModelHealthSnapshot.manual_override"`)}
	}
	if _, ok := _c.mutation.ProbedAt(); !ok {
		return &ValidationError{Name: "probed_at", err: errors.New(`ent: missing required field "ModelHealthSnapshot.probed_at"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ModelHealthSnapshot.channel"`)}
	}
	return nil
}

func (_c *ModelHealthSnapshotCreate) sqlSave(ctx context.Context) (*ModelHealthSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelHealthSnapshotCreate) createSpec() (*ModelHealthSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelHealthSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelhealthsnapshot.Table, sqlgraph.NewFieldSpec(modelhealthsnapshot.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelhealthsnapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelhealthsnapshot.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DisplayModel(); ok {
		_spec.SetField(modelhealthsnapshot.FieldDisplayModel, field.TypeString, value)
		_node.DisplayModel = value
	}
	if value, ok := _c.mutation.ActualModelID(); ok {
		_spec.SetField(modelhealthsnapshot.FieldActualModelID, field.TypeString, value)
		_node.ActualModelID = value
	}
	if value, ok := _c.mutation.IsHealthy(); ok {
		_spec.SetField(modelhealthsnapshot.FieldIsHealthy, field.TypeBool, value)
		_node.IsHealthy = value
	}
	if value, ok := _c.mutation.ManualOverride(); ok {
		_spec.SetField(modelhealthsnapshot.FieldManualOverride, field.TypeBool, value)
		_node.ManualOverride = value
	}
	if value, ok := _c.mutation.ProbedAt(); ok {
		_spec.SetField(modelhealthsnapshot.FieldProbedAt, field.TypeInt64, value)
		_node.ProbedAt = value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelhealthsnapshot.ChannelTable,
			Columns: []string{modelhealthsnapshot.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelHealthSnapshot.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelHealthSnapshotUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelHealthSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *ModelHealthSnapshotUpsertOne {
	_c.conflict = opts
	return &ModelHealthSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelHealthSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelHealthSnapshotCreate) OnConflictColumns(columns ...string) *ModelHealthSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelHealthSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// ModelHealthSnapshotUpsertOne is the builder for "upsert"-ing
	//  one ModelHealthSnapshot node.
	ModelHealthSnapshotUpsertOne struct {
		create *ModelHealthSnapshotCreate
	}

	// ModelHealthSnapshotUpsert is the "OnConflict" setter.
	ModelHealthSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelHealthSnapshotUpsert) SetUpdatedAt(v time.Time) *ModelHealthSnapshotUpsert {
	u.Set(modelhealthsnapshot.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsert) UpdateUpdatedAt() *ModelHealthSnapshotUpsert {
	u.SetExcluded(modelhealthsnapshot.FieldUpdatedAt)
	return u
}

// SetDisplayModel sets the "display_model" field.
func (u *ModelHealthSnapshotUpsert) SetDisplayModel(v string) *ModelHealthSnapshotUpsert {
	u.Set(modelhealthsnapshot.FieldDisplayModel, v)
	return u
}

// UpdateDisplayModel sets the "display_model" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsert) UpdateDisplayModel() *ModelHealthSnapshotUpsert {
	u.SetExcluded(modelhealthsnapshot.FieldDisplayModel)
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *ModelHealthSnapshotUpsert) SetChannelID(v int) *ModelHealthSnapshotUpsert {
	u.Set(modelhealthsnapshot.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsert) UpdateChannelID() *ModelHealthSnapshotUpsert {
	u.SetExcluded(modelhealthsnapshot.FieldChannelID)
	return u
}

// SetActualModelID sets the "actual_model_id" field.
func (u *ModelHealthSnapshotUpsert) SetActualModelID(v string) *ModelHealthSnapshotUpsert {
	u.Set(modelhealthsnapshot.FieldActualModelID, v)
	return u
}

// UpdateActualModelID sets the "actual_model_id" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsert) UpdateActualModelID() *ModelHealthSnapshotUpsert {
	u.SetExcluded(modelhealthsnapshot.FieldActualModelID)
	return u
}

// SetIsHealthy sets the "is_healthy" field.
func (u *ModelHealthSnapshotUpsert) SetIsHealthy(v bool) *ModelHealthSnapshotUpsert {
	u.Set(modelhealthsnapshot.FieldIsHealthy, v)
	return u
}

// UpdateIsHealthy sets the "is_healthy" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsert) UpdateIsHealthy() *ModelHealthSnapshotUpsert {
	u.SetExcluded(modelhealthsnapshot.FieldIsHealthy)
	return u
}

// SetManualOverride sets the "manual_override" field.
func (u *ModelHealthSnapshotUpsert) SetManualOverride(v bool) *ModelHealthSnapshotUpsert {
	u.Set(modelhealthsnapshot.FieldManualOverride, v)
	return u
}

// UpdateManualOverride sets the "manual_override" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsert) UpdateManualOverride() *ModelHealthSnapshotUpsert {
	u.SetExcluded(modelhealthsnapshot.FieldManualOverride)
	return u
}

// SetProbedAt sets the "probed_at" field.
func (u *ModelHealthSnapshotUpsert) SetProbedAt(v int64) *ModelHealthSnapshotUpsert {
	u.Set(modelhealthsnapshot.FieldProbedAt, v)
	return u
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsert) UpdateProbedAt() *ModelHealthSnapshotUpsert {
	u.SetExcluded(modelhealthsnapshot.FieldProbedAt)
	return u
}

// AddProbedAt adds v to the "probed_at" field.
func (u *ModelHealthSnapshotUpsert) AddProbedAt(v int64) *ModelHealthSnapshotUpsert {
	u.Add(modelhealthsnapshot.FieldProbedAt, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelHealthSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelHealthSnapshotUpsertOne) UpdateNewValues() *ModelHealthSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelhealthsnapshot.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelHealthSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelHealthSnapshotUpsertOne) Ignore() *ModelHealthSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelHealthSnapshotUpsertOne) DoNothing() *ModelHealthSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelHealthSnapshotCreate.OnConflict
// documentation for more info.
func (u *ModelHealthSnapshotUpsertOne) Update(set func(*ModelHealthSnapshotUpsert)) *ModelHealthSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelHealthSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelHealthSnapshotUpsertOne) SetUpdatedAt(v time.Time) *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertOne) UpdateUpdatedAt() *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDisplayModel sets the "display_model" field.
func (u *ModelHealthSnapshotUpsertOne) SetDisplayModel(v string) *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetDisplayModel(v)
	})
}

// UpdateDisplayModel sets the "display_model" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertOne) UpdateDisplayModel() *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateDisplayModel()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *ModelHealthSnapshotUpsertOne) SetChannelID(v int) *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertOne) UpdateChannelID() *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateChannelID()
	})
}

// SetActualModelID sets the "actual_model_id" field.
func (u *ModelHealthSnapshotUpsertOne) SetActualModelID(v string) *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetActualModelID(v)
	})
}

// UpdateActualModelID sets the "actual_model_id" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertOne) UpdateActualModelID() *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateActualModelID()
	})
}

// SetIsHealthy sets the "is_healthy" field.
func (u *ModelHealthSnapshotUpsertOne) SetIsHealthy(v bool) *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetIsHealthy(v)
	})
}

// UpdateIsHealthy sets the "is_healthy" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertOne) UpdateIsHealthy() *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateIsHealthy()
	})
}

// SetManualOverride sets the "manual_override" field.
func (u *ModelHealthSnapshotUpsertOne) SetManualOverride(v bool) *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetManualOverride(v)
	})
}

// UpdateManualOverride sets the "manual_override" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertOne) UpdateManualOverride() *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateManualOverride()
	})
}

// SetProbedAt sets the "probed_at" field.
func (u *ModelHealthSnapshotUpsertOne) SetProbedAt(v int64) *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetProbedAt(v)
	})
}

// AddProbedAt adds v to the "probed_at" field.
func (u *ModelHealthSnapshotUpsertOne) AddProbedAt(v int64) *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.AddProbedAt(v)
	})
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertOne) UpdateProbedAt() *ModelHealthSnapshotUpsertOne {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateProbedAt()
	})
}

// Exec executes the query.
func (u *ModelHealthSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelHealthSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelHealthSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelHealthSnapshotUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelHealthSnapshotUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelHealthSnapshotCreateBulk is the builder for creating many ModelHealthSnapshot entities in bulk.
type ModelHealthSnapshotCreateBulk struct {
	config
	err      error
	builders []*ModelHealthSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelHealthSnapshot entities in the database.
func (_c *ModelHealthSnapshotCreateBulk) Save(ctx context.Context) ([]*ModelHealthSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelHealthSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelHealthSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelHealthSnapshotCreateBulk) SaveX(ctx context.Context) []*ModelHealthSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelHealthSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelHealthSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelHealthSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelHealthSnapshotUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelHealthSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelHealthSnapshotUpsertBulk {
	_c.conflict = opts
	return &ModelHealthSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelHealthSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelHealthSnapshotCreateBulk) OnConflictColumns(columns ...string) *ModelHealthSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelHealthSnapshotUpsertBulk{
		create: _c,
	}
}

// ModelHealthSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelHealthSnapshot nodes.
type ModelHealthSnapshotUpsertBulk struct {
	create *ModelHealthSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelHealthSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelHealthSnapshotUpsertBulk) UpdateNewValues() *ModelHealthSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelhealthsnapshot.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelHealthSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelHealthSnapshotUpsertBulk) Ignore() *ModelHealthSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelHealthSnapshotUpsertBulk) DoNothing() *ModelHealthSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelHealthSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *ModelHealthSnapshotUpsertBulk) Update(set func(*ModelHealthSnapshotUpsert)) *ModelHealthSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelHealthSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelHealthSnapshotUpsertBulk) SetUpdatedAt(v time.Time) *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertBulk) UpdateUpdatedAt() *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDisplayModel sets the "display_model" field.
func (u *ModelHealthSnapshotUpsertBulk) SetDisplayModel(v string) *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetDisplayModel(v)
	})
}

// UpdateDisplayModel sets the "display_model" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertBulk) UpdateDisplayModel() *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateDisplayModel()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *ModelHealthSnapshotUpsertBulk) SetChannelID(v int) *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertBulk) UpdateChannelID() *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateChannelID()
	})
}

// SetActualModelID sets the "actual_model_id" field.
func (u *ModelHealthSnapshotUpsertBulk) SetActualModelID(v string) *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetActualModelID(v)
	})
}

// UpdateActualModelID sets the "actual_model_id" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertBulk) UpdateActualModelID() *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateActualModelID()
	})
}

// SetIsHealthy sets the "is_healthy" field.
func (u *ModelHealthSnapshotUpsertBulk) SetIsHealthy(v bool) *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetIsHealthy(v)
	})
}

// UpdateIsHealthy sets the "is_healthy" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertBulk) UpdateIsHealthy() *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateIsHealthy()
	})
}

// SetManualOverride sets the "manual_override" field.
func (u *ModelHealthSnapshotUpsertBulk) SetManualOverride(v bool) *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetManualOverride(v)
	})
}

// UpdateManualOverride sets the "manual_override" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertBulk) UpdateManualOverride() *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateManualOverride()
	})
}

// SetProbedAt sets the "probed_at" field.
func (u *ModelHealthSnapshotUpsertBulk) SetProbedAt(v int64) *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.SetProbedAt(v)
	})
}

// AddProbedAt adds v to the "probed_at" field.
func (u *ModelHealthSnapshotUpsertBulk) AddProbedAt(v int64) *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.AddProbedAt(v)
	})
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *ModelHealthSnapshotUpsertBulk) UpdateProbedAt() *ModelHealthSnapshotUpsertBulk {
	return u.Update(func(s *ModelHealthSnapshotUpsert) {
		s.UpdateProbedAt()
	})
}

// Exec executes the query.
func (u *ModelHealthSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelHealthSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelHealthSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelHealthSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
