// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/modelhealthsnapshot"
)

// ModelHealthSnapshot is the model entity for the ModelHealthSnapshot schema.
type ModelHealthSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DisplayModel holds the value of the "display_model" field.
	DisplayModel string `json:"display_model,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int `json:"channel_id,omitempty"`
	// ActualModelID holds the value of the "actual_model_id" field.
	ActualModelID string `json:"actual_model_id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// IsHealthy holds the value of the "is_healthy" field.
	IsHealthy bool `json:"is_healthy,omitempty"`
	// ManualOverride holds the value of the "manual_override" field.
	ManualOverride bool `json:"manual_override,omitempty"`
	// ProbedAt holds the value of the "probed_at" field.
	ProbedAt int64 `json:"probed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelHealthSnapshotQuery when eager-loading is set.
	Edges        ModelHealthSnapshotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelHealthSnapshotEdges holds the relations/edges for other nodes in the graph.
type ModelHealthSnapshotEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModelHealthSnapshotEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelHealthSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelhealthsnapshot.FieldIsHealthy, modelhealthsnapshot.FieldManualOverride:
			values[i] = new(sql.NullBool)
		case modelhealthsnapshot.FieldID, modelhealthsnapshot.FieldChannelID, modelhealthsnapshot.FieldProbedAt:
			values[i] = new(sql.NullInt64)
		case modelhealthsnapshot.FieldDisplayModel, modelhealthsnapshot.FieldActualModelID, modelhealthsnapshot.FieldSource:
			values[i] = new(sql.NullString)
		case modelhealthsnapshot.FieldCreatedAt, modelhealthsnapshot.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelHealthSnapshot fields.
func (_m *ModelHealthSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelhealthsnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case modelhealthsnapshot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelhealthsnapshot.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelhealthsnapshot.FieldDisplayModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_model", values[i])
			} else if value.Valid {
				_m.DisplayModel = value.String
			}
		case modelhealthsnapshot.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case modelhealthsnapshot.FieldActualModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actual_model_id", values[i])
			} else if value.Valid {
				_m.ActualModelID = value.String
			}
		case modelhealthsnapshot.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case modelhealthsnapshot.FieldIsHealthy:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_healthy", values[i])
			} else if value.Valid {
				_m.IsHealthy = value.Bool
			}
		case modelhealthsnapshot.FieldManualOverride:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field manual_override", values[i])
			} else if value.Valid {
				_m.ManualOverride = value.Bool
			}
		case modelhealthsnapshot.FieldProbedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field probed_at", values[i])
			} else if value.Valid {
				_m.ProbedAt = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelHealthSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *ModelHealthSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the ModelHealthSnapshot entity.
func (_m *ModelHealthSnapshot) QueryChannel() *ChannelQuery {
	return NewModelHealthSnapshotClient(_m.config).QueryChannel(_m)
}

// Update returns a builder for updating this ModelHealthSnapshot.
// Note that you need to call ModelHealthSnapshot.Unwrap() before calling this method if this ModelHealthSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelHealthSnapshot) Update() *ModelHealthSnapshotUpdateOne {
	return NewModelHealthSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelHealthSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelHealthSnapshot) Unwrap() *ModelHealthSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelHealthSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelHealthSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("ModelHealthSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("display_model=")
	builder.WriteString(_m.DisplayModel)
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("actual_model_id=")
	builder.WriteString(_m.ActualModelID)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("is_healthy=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsHealthy))
	builder.WriteString(", ")
	builder.WriteString("manual_override=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManualOverride))
	builder.WriteString(", ")
	builder.WriteString("probed_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProbedAt))
	builder.WriteByte(')')
	return builder.String()
}

// ModelHealthSnapshots is a parsable slice of ModelHealthSnapshot.
type ModelHealthSnapshots []*ModelHealthSnapshot
