// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/modelprobeconfig"
)

// ModelProbeConfig is the model entity for the ModelProbeConfig schema.
type ModelProbeConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DisplayModel holds the value of the "display_model" field.
	DisplayModel string `json:"display_model,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int `json:"channel_id,omitempty"`
	// ActualModelID holds the value of the "actual_model_id" field.
	ActualModelID string `json:"actual_model_id,omitempty"`
	// ProbeEnabled holds the value of the "probe_enabled" field.
	ProbeEnabled bool `json:"probe_enabled,omitempty"`
	// ConsecutiveFailures holds the value of the "consecutive_failures" field.
	ConsecutiveFailures int `json:"consecutive_failures,omitempty"`
	// AutoDisabledAt holds the value of the "auto_disabled_at" field.
	AutoDisabledAt *int64 `json:"auto_disabled_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelProbeConfigQuery when eager-loading is set.
	Edges        ModelProbeConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelProbeConfigEdges holds the relations/edges for other nodes in the graph.
type ModelProbeConfigEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModelProbeConfigEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelProbeConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelprobeconfig.FieldProbeEnabled:
			values[i] = new(sql.NullBool)
		case modelprobeconfig.FieldID, modelprobeconfig.FieldChannelID, modelprobeconfig.FieldConsecutiveFailures, modelprobeconfig.FieldAutoDisabledAt:
			values[i] = new(sql.NullInt64)
		case modelprobeconfig.FieldDisplayModel, modelprobeconfig.FieldActualModelID:
			values[i] = new(sql.NullString)
		case modelprobeconfig.FieldCreatedAt, modelprobeconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelProbeConfig fields.
func (_m *ModelProbeConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelprobeconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case modelprobeconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelprobeconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelprobeconfig.FieldDisplayModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_model", values[i])
			} else if value.Valid {
				_m.DisplayModel = value.String
			}
		case modelprobeconfig.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case modelprobeconfig.FieldActualModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actual_model_id", values[i])
			} else if value.Valid {
				_m.ActualModelID = value.String
			}
		case modelprobeconfig.FieldProbeEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field probe_enabled", values[i])
			} else if value.Valid {
				_m.ProbeEnabled = value.Bool
			}
		case modelprobeconfig.FieldConsecutiveFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_failures", values[i])
			} else if value.Valid {
				_m.ConsecutiveFailures = int(value.Int64)
			}
		case modelprobeconfig.FieldAutoDisabledAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field auto_disabled_at", values[i])
			} else if value.Valid {
				_m.AutoDisabledAt = new(int64)
				*_m.AutoDisabledAt = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelProbeConfig.
// This includes values selected through modifiers, order, etc.
func (_m *ModelProbeConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the ModelProbeConfig entity.
func (_m *ModelProbeConfig) QueryChannel() *ChannelQuery {
	return NewModelProbeConfigClient(_m.config).QueryChannel(_m)
}

// Update returns a builder for updating this ModelProbeConfig.
// Note that you need to call ModelProbeConfig.Unwrap() before calling this method if this ModelProbeConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelProbeConfig) Update() *ModelProbeConfigUpdateOne {
	return NewModelProbeConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelProbeConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelProbeConfig) Unwrap() *ModelProbeConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelProbeConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelProbeConfig) String() string {
	var builder strings.Builder
	builder.WriteString("ModelProbeConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("display_model=")
	builder.WriteString(_m.DisplayModel)
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("actual_model_id=")
	builder.WriteString(_m.ActualModelID)
	builder.WriteString(", ")
	builder.WriteString("probe_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProbeEnabled))
	builder.WriteString(", ")
	builder.WriteString("consecutive_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveFailures))
	builder.WriteString(", ")
	if v := _m.AutoDisabledAt; v != nil {
		builder.WriteString("auto_disabled_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ModelProbeConfigs is a parsable slice of ModelProbeConfig.
type ModelProbeConfigs []*ModelProbeConfig
