// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/runtimelog"
)

// RuntimeLogUpdate is the builder for updating RuntimeLog entities.
type RuntimeLogUpdate struct {
	config
	hooks     []Hook
	mutation  *RuntimeLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RuntimeLogUpdate builder.
func (_u *RuntimeLogUpdate) Where(ps ...predicate.RuntimeLog) *RuntimeLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RuntimeLogUpdate) SetUpdatedAt(v time.Time) *RuntimeLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLogger sets the "logger" field.
func (_u *RuntimeLogUpdate) SetLogger(v string) *RuntimeLogUpdate {
	_u.mutation.SetLogger(v)
	return _u
}

// SetNillableLogger sets the "logger" field if the given value is not nil.
func (_u *RuntimeLogUpdate) SetNillableLogger(v *string) *RuntimeLogUpdate {
	if v != nil {
		_u.SetLogger(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *RuntimeLogUpdate) SetLevel(v runtimelog.Level) *RuntimeLogUpdate {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *RuntimeLogUpdate) SetNillableLevel(v *runtimelog.Level) *RuntimeLogUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *RuntimeLogUpdate) SetMessage(v string) *RuntimeLogUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *RuntimeLogUpdate) SetNillableMessage(v *string) *RuntimeLogUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetCaller sets the "caller" field.
func (_u *RuntimeLogUpdate) SetCaller(v string) *RuntimeLogUpdate {
	_u.mutation.SetCaller(v)
	return _u
}

// SetNillableCaller sets the "caller" field if the given value is not nil.
func (_u *RuntimeLogUpdate) SetNillableCaller(v *string) *RuntimeLogUpdate {
	if v != nil {
		_u.SetCaller(*v)
	}
	return _u
}

// ClearCaller clears the value of the "caller" field.
func (_u *RuntimeLogUpdate) ClearCaller() *RuntimeLogUpdate {
	_u.mutation.ClearCaller()
	return _u
}

// SetTraceID sets the "trace_id" field.
func (_u *RuntimeLogUpdate) SetTraceID(v string) *RuntimeLogUpdate {
	_u.mutation.SetTraceID(v)
	return _u
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_u *RuntimeLogUpdate) SetNillableTraceID(v *string) *RuntimeLogUpdate {
	if v != nil {
		_u.SetTraceID(*v)
	}
	return _u
}

// ClearTraceID clears the value of the "trace_id" field.
func (_u *RuntimeLogUpdate) ClearTraceID() *RuntimeLogUpdate {
	_u.mutation.ClearTraceID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RuntimeLogUpdate) SetRequestID(v string) *RuntimeLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RuntimeLogUpdate) SetNillableRequestID(v *string) *RuntimeLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RuntimeLogUpdate) ClearRequestID() *RuntimeLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetOperationName sets the "operation_name" field.
func (_u *RuntimeLogUpdate) SetOperationName(v string) *RuntimeLogUpdate {
	_u.mutation.SetOperationName(v)
	return _u
}

// SetNillableOperationName sets the "operation_name" field if the given value is not nil.
func (_u *RuntimeLogUpdate) SetNillableOperationName(v *string) *RuntimeLogUpdate {
	if v != nil {
		_u.SetOperationName(*v)
	}
	return _u
}

// ClearOperationName clears the value of the "operation_name" field.
func (_u *RuntimeLogUpdate) ClearOperationName() *RuntimeLogUpdate {
	_u.mutation.ClearOperationName()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *RuntimeLogUpdate) SetChannelID(v int) *RuntimeLogUpdate {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *RuntimeLogUpdate) SetNillableChannelID(v *int) *RuntimeLogUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *RuntimeLogUpdate) AddChannelID(v int) *RuntimeLogUpdate {
	_u.mutation.AddChannelID(v)
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *RuntimeLogUpdate) ClearChannelID() *RuntimeLogUpdate {
	_u.mutation.ClearChannelID()
	return _u
}

// SetChannelName sets the "channel_name" field.
func (_u *RuntimeLogUpdate) SetChannelName(v string) *RuntimeLogUpdate {
	_u.mutation.SetChannelName(v)
	return _u
}

// SetNillableChannelName sets the "channel_name" field if the given value is not nil.
func (_u *RuntimeLogUpdate) SetNillableChannelName(v *string) *RuntimeLogUpdate {
	if v != nil {
		_u.SetChannelName(*v)
	}
	return _u
}

// ClearChannelName clears the value of the "channel_name" field.
func (_u *RuntimeLogUpdate) ClearChannelName() *RuntimeLogUpdate {
	_u.mutation.ClearChannelName()
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *RuntimeLogUpdate) SetModelID(v string) *RuntimeLogUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *RuntimeLogUpdate) SetNillableModelID(v *string) *RuntimeLogUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// ClearModelID clears the value of the "model_id" field.
func (_u *RuntimeLogUpdate) ClearModelID() *RuntimeLogUpdate {
	_u.mutation.ClearModelID()
	return _u
}

// SetFieldsJSON sets the "fields_json" field.
func (_u *RuntimeLogUpdate) SetFieldsJSON(v map[string]interface{}) *RuntimeLogUpdate {
	_u.mutation.SetFieldsJSON(v)
	return _u
}

// Mutation returns the RuntimeLogMutation object of the builder.
func (_u *RuntimeLogUpdate) Mutation() *RuntimeLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RuntimeLogUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuntimeLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RuntimeLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuntimeLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RuntimeLogUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if runtimelog.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized runtimelog.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := runtimelog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuntimeLogUpdate) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := runtimelog.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "RuntimeLog.level": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RuntimeLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RuntimeLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RuntimeLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(runtimelog.Table, runtimelog.Columns, sqlgraph.NewFieldSpec(runtimelog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(runtimelog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Logger(); ok {
		_spec.SetField(runtimelog.FieldLogger, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(runtimelog.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(runtimelog.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Caller(); ok {
		_spec.SetField(runtimelog.FieldCaller, field.TypeString, value)
	}
	if _u.mutation.CallerCleared() {
		_spec.ClearField(runtimelog.FieldCaller, field.TypeString)
	}
	if value, ok := _u.mutation.TraceID(); ok {
		_spec.SetField(runtimelog.FieldTraceID, field.TypeString, value)
	}
	if _u.mutation.TraceIDCleared() {
		_spec.ClearField(runtimelog.FieldTraceID, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(runtimelog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(runtimelog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.OperationName(); ok {
		_spec.SetField(runtimelog.FieldOperationName, field.TypeString, value)
	}
	if _u.mutation.OperationNameCleared() {
		_spec.ClearField(runtimelog.FieldOperationName, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(runtimelog.FieldChannelID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(runtimelog.FieldChannelID, field.TypeInt, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(runtimelog.FieldChannelID, field.TypeInt)
	}
	if value, ok := _u.mutation.ChannelName(); ok {
		_spec.SetField(runtimelog.FieldChannelName, field.TypeString, value)
	}
	if _u.mutation.ChannelNameCleared() {
		_spec.ClearField(runtimelog.FieldChannelName, field.TypeString)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(runtimelog.FieldModelID, field.TypeString, value)
	}
	if _u.mutation.ModelIDCleared() {
		_spec.ClearField(runtimelog.FieldModelID, field.TypeString)
	}
	if value, ok := _u.mutation.FieldsJSON(); ok {
		_spec.SetField(runtimelog.FieldFieldsJSON, field.TypeJSON, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runtimelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RuntimeLogUpdateOne is the builder for updating a single RuntimeLog entity.
type RuntimeLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RuntimeLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RuntimeLogUpdateOne) SetUpdatedAt(v time.Time) *RuntimeLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLogger sets the "logger" field.
func (_u *RuntimeLogUpdateOne) SetLogger(v string) *RuntimeLogUpdateOne {
	_u.mutation.SetLogger(v)
	return _u
}

// SetNillableLogger sets the "logger" field if the given value is not nil.
func (_u *RuntimeLogUpdateOne) SetNillableLogger(v *string) *RuntimeLogUpdateOne {
	if v != nil {
		_u.SetLogger(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *RuntimeLogUpdateOne) SetLevel(v runtimelog.Level) *RuntimeLogUpdateOne {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *RuntimeLogUpdateOne) SetNillableLevel(v *runtimelog.Level) *RuntimeLogUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *RuntimeLogUpdateOne) SetMessage(v string) *RuntimeLogUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *RuntimeLogUpdateOne) SetNillableMessage(v *string) *RuntimeLogUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetCaller sets the "caller" field.
func (_u *RuntimeLogUpdateOne) SetCaller(v string) *RuntimeLogUpdateOne {
	_u.mutation.SetCaller(v)
	return _u
}

// SetNillableCaller sets the "caller" field if the given value is not nil.
func (_u *RuntimeLogUpdateOne) SetNillableCaller(v *string) *RuntimeLogUpdateOne {
	if v != nil {
		_u.SetCaller(*v)
	}
	return _u
}

// ClearCaller clears the value of the "caller" field.
func (_u *RuntimeLogUpdateOne) ClearCaller() *RuntimeLogUpdateOne {
	_u.mutation.ClearCaller()
	return _u
}

// SetTraceID sets the "trace_id" field.
func (_u *RuntimeLogUpdateOne) SetTraceID(v string) *RuntimeLogUpdateOne {
	_u.mutation.SetTraceID(v)
	return _u
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_u *RuntimeLogUpdateOne) SetNillableTraceID(v *string) *RuntimeLogUpdateOne {
	if v != nil {
		_u.SetTraceID(*v)
	}
	return _u
}

// ClearTraceID clears the value of the "trace_id" field.
func (_u *RuntimeLogUpdateOne) ClearTraceID() *RuntimeLogUpdateOne {
	_u.mutation.ClearTraceID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RuntimeLogUpdateOne) SetRequestID(v string) *RuntimeLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RuntimeLogUpdateOne) SetNillableRequestID(v *string) *RuntimeLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RuntimeLogUpdateOne) ClearRequestID() *RuntimeLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetOperationName sets the "operation_name" field.
func (_u *RuntimeLogUpdateOne) SetOperationName(v string) *RuntimeLogUpdateOne {
	_u.mutation.SetOperationName(v)
	return _u
}

// SetNillableOperationName sets the "operation_name" field if the given value is not nil.
func (_u *RuntimeLogUpdateOne) SetNillableOperationName(v *string) *RuntimeLogUpdateOne {
	if v != nil {
		_u.SetOperationName(*v)
	}
	return _u
}

// ClearOperationName clears the value of the "operation_name" field.
func (_u *RuntimeLogUpdateOne) ClearOperationName() *RuntimeLogUpdateOne {
	_u.mutation.ClearOperationName()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *RuntimeLogUpdateOne) SetChannelID(v int) *RuntimeLogUpdateOne {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *RuntimeLogUpdateOne) SetNillableChannelID(v *int) *RuntimeLogUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *RuntimeLogUpdateOne) AddChannelID(v int) *RuntimeLogUpdateOne {
	_u.mutation.AddChannelID(v)
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *RuntimeLogUpdateOne) ClearChannelID() *RuntimeLogUpdateOne {
	_u.mutation.ClearChannelID()
	return _u
}

// SetChannelName sets the "channel_name" field.
func (_u *RuntimeLogUpdateOne) SetChannelName(v string) *RuntimeLogUpdateOne {
	_u.mutation.SetChannelName(v)
	return _u
}

// SetNillableChannelName sets the "channel_name" field if the given value is not nil.
func (_u *RuntimeLogUpdateOne) SetNillableChannelName(v *string) *RuntimeLogUpdateOne {
	if v != nil {
		_u.SetChannelName(*v)
	}
	return _u
}

// ClearChannelName clears the value of the "channel_name" field.
func (_u *RuntimeLogUpdateOne) ClearChannelName() *RuntimeLogUpdateOne {
	_u.mutation.ClearChannelName()
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *RuntimeLogUpdateOne) SetModelID(v string) *RuntimeLogUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *RuntimeLogUpdateOne) SetNillableModelID(v *string) *RuntimeLogUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// ClearModelID clears the value of the "model_id" field.
func (_u *RuntimeLogUpdateOne) ClearModelID() *RuntimeLogUpdateOne {
	_u.mutation.ClearModelID()
	return _u
}

// SetFieldsJSON sets the "fields_json" field.
func (_u *RuntimeLogUpdateOne) SetFieldsJSON(v map[string]interface{}) *RuntimeLogUpdateOne {
	_u.mutation.SetFieldsJSON(v)
	return _u
}

// Mutation returns the RuntimeLogMutation object of the builder.
func (_u *RuntimeLogUpdateOne) Mutation() *RuntimeLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the RuntimeLogUpdate builder.
func (_u *RuntimeLogUpdateOne) Where(ps ...predicate.RuntimeLog) *RuntimeLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RuntimeLogUpdateOne) Select(field string, fields ...string) *RuntimeLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RuntimeLog entity.
func (_u *RuntimeLogUpdateOne) Save(ctx context.Context) (*RuntimeLog, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuntimeLogUpdateOne) SaveX(ctx context.Context) *RuntimeLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RuntimeLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuntimeLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RuntimeLogUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if runtimelog.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized runtimelog.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := runtimelog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuntimeLogUpdateOne) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := runtimelog.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "RuntimeLog.level": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RuntimeLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RuntimeLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RuntimeLogUpdateOne) sqlSave(ctx context.Context) (_node *RuntimeLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(runtimelog.Table, runtimelog.Columns, sqlgraph.NewFieldSpec(runtimelog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RuntimeLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, runtimelog.FieldID)
		for _, f := range fields {
			if !runtimelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != runtimelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(runtimelog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Logger(); ok {
		_spec.SetField(runtimelog.FieldLogger, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(runtimelog.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(runtimelog.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Caller(); ok {
		_spec.SetField(runtimelog.FieldCaller, field.TypeString, value)
	}
	if _u.mutation.CallerCleared() {
		_spec.ClearField(runtimelog.FieldCaller, field.TypeString)
	}
	if value, ok := _u.mutation.TraceID(); ok {
		_spec.SetField(runtimelog.FieldTraceID, field.TypeString, value)
	}
	if _u.mutation.TraceIDCleared() {
		_spec.ClearField(runtimelog.FieldTraceID, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(runtimelog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(runtimelog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.OperationName(); ok {
		_spec.SetField(runtimelog.FieldOperationName, field.TypeString, value)
	}
	if _u.mutation.OperationNameCleared() {
		_spec.ClearField(runtimelog.FieldOperationName, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(runtimelog.FieldChannelID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(runtimelog.FieldChannelID, field.TypeInt, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(runtimelog.FieldChannelID, field.TypeInt)
	}
	if value, ok := _u.mutation.ChannelName(); ok {
		_spec.SetField(runtimelog.FieldChannelName, field.TypeString, value)
	}
	if _u.mutation.ChannelNameCleared() {
		_spec.ClearField(runtimelog.FieldChannelName, field.TypeString)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(runtimelog.FieldModelID, field.TypeString, value)
	}
	if _u.mutation.ModelIDCleared() {
		_spec.ClearField(runtimelog.FieldModelID, field.TypeString)
	}
	if value, ok := _u.mutation.FieldsJSON(); ok {
		_spec.SetField(runtimelog.FieldFieldsJSON, field.TypeJSON, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RuntimeLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runtimelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
