// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/runtimelog"
)

// RuntimeLog is the model entity for the RuntimeLog schema.
type RuntimeLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Logger holds the value of the "logger" field.
	Logger string `json:"logger,omitempty"`
	// Level holds the value of the "level" field.
	Level runtimelog.Level `json:"level,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// Caller holds the value of the "caller" field.
	Caller string `json:"caller,omitempty"`
	// TraceID holds the value of the "trace_id" field.
	TraceID *string `json:"trace_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// OperationName holds the value of the "operation_name" field.
	OperationName *string `json:"operation_name,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID *int `json:"channel_id,omitempty"`
	// ChannelName holds the value of the "channel_name" field.
	ChannelName *string `json:"channel_name,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID *string `json:"model_id,omitempty"`
	// FieldsJSON holds the value of the "fields_json" field.
	FieldsJSON   map[string]interface{} `json:"fields_json,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RuntimeLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case runtimelog.FieldFieldsJSON:
			values[i] = new([]byte)
		case runtimelog.FieldID, runtimelog.FieldChannelID:
			values[i] = new(sql.NullInt64)
		case runtimelog.FieldLogger, runtimelog.FieldLevel, runtimelog.FieldMessage, runtimelog.FieldCaller, runtimelog.FieldTraceID, runtimelog.FieldRequestID, runtimelog.FieldOperationName, runtimelog.FieldChannelName, runtimelog.FieldModelID:
			values[i] = new(sql.NullString)
		case runtimelog.FieldCreatedAt, runtimelog.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RuntimeLog fields.
func (_m *RuntimeLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case runtimelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case runtimelog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case runtimelog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case runtimelog.FieldLogger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logger", values[i])
			} else if value.Valid {
				_m.Logger = value.String
			}
		case runtimelog.FieldLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = runtimelog.Level(value.String)
			}
		case runtimelog.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case runtimelog.FieldCaller:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field caller", values[i])
			} else if value.Valid {
				_m.Caller = value.String
			}
		case runtimelog.FieldTraceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trace_id", values[i])
			} else if value.Valid {
				_m.TraceID = new(string)
				*_m.TraceID = value.String
			}
		case runtimelog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case runtimelog.FieldOperationName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation_name", values[i])
			} else if value.Valid {
				_m.OperationName = new(string)
				*_m.OperationName = value.String
			}
		case runtimelog.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = new(int)
				*_m.ChannelID = int(value.Int64)
			}
		case runtimelog.FieldChannelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_name", values[i])
			} else if value.Valid {
				_m.ChannelName = new(string)
				*_m.ChannelName = value.String
			}
		case runtimelog.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = new(string)
				*_m.ModelID = value.String
			}
		case runtimelog.FieldFieldsJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field fields_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.FieldsJSON); err != nil {
					return fmt.Errorf("unmarshal field fields_json: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RuntimeLog.
// This includes values selected through modifiers, order, etc.
func (_m *RuntimeLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RuntimeLog.
// Note that you need to call RuntimeLog.Unwrap() before calling this method if this RuntimeLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RuntimeLog) Update() *RuntimeLogUpdateOne {
	return NewRuntimeLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RuntimeLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RuntimeLog) Unwrap() *RuntimeLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RuntimeLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RuntimeLog) String() string {
	var builder strings.Builder
	builder.WriteString("RuntimeLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("logger=")
	builder.WriteString(_m.Logger)
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", _m.Level))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("caller=")
	builder.WriteString(_m.Caller)
	builder.WriteString(", ")
	if v := _m.TraceID; v != nil {
		builder.WriteString("trace_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OperationName; v != nil {
		builder.WriteString("operation_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ChannelID; v != nil {
		builder.WriteString("channel_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ChannelName; v != nil {
		builder.WriteString("channel_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ModelID; v != nil {
		builder.WriteString("model_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("fields_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.FieldsJSON))
	builder.WriteByte(')')
	return builder.String()
}

// RuntimeLogs is a parsable slice of RuntimeLog.
type RuntimeLogs []*RuntimeLog
