// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/runtimelog"
)

// RuntimeLogCreate is the builder for creating a RuntimeLog entity.
type RuntimeLogCreate struct {
	config
	mutation *RuntimeLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RuntimeLogCreate) SetCreatedAt(v time.Time) *RuntimeLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RuntimeLogCreate) SetNillableCreatedAt(v *time.Time) *RuntimeLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RuntimeLogCreate) SetUpdatedAt(v time.Time) *RuntimeLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RuntimeLogCreate) SetNillableUpdatedAt(v *time.Time) *RuntimeLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLogger sets the "logger" field.
func (_c *RuntimeLogCreate) SetLogger(v string) *RuntimeLogCreate {
	_c.mutation.SetLogger(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *RuntimeLogCreate) SetLevel(v runtimelog.Level) *RuntimeLogCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *RuntimeLogCreate) SetMessage(v string) *RuntimeLogCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetCaller sets the "caller" field.
func (_c *RuntimeLogCreate) SetCaller(v string) *RuntimeLogCreate {
	_c.mutation.SetCaller(v)
	return _c
}

// SetNillableCaller sets the "caller" field if the given value is not nil.
func (_c *RuntimeLogCreate) SetNillableCaller(v *string) *RuntimeLogCreate {
	if v != nil {
		_c.SetCaller(*v)
	}
	return _c
}

// SetTraceID sets the "trace_id" field.
func (_c *RuntimeLogCreate) SetTraceID(v string) *RuntimeLogCreate {
	_c.mutation.SetTraceID(v)
	return _c
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_c *RuntimeLogCreate) SetNillableTraceID(v *string) *RuntimeLogCreate {
	if v != nil {
		_c.SetTraceID(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *RuntimeLogCreate) SetRequestID(v string) *RuntimeLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *RuntimeLogCreate) SetNillableRequestID(v *string) *RuntimeLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetOperationName sets the "operation_name" field.
func (_c *RuntimeLogCreate) SetOperationName(v string) *RuntimeLogCreate {
	_c.mutation.SetOperationName(v)
	return _c
}

// SetNillableOperationName sets the "operation_name" field if the given value is not nil.
func (_c *RuntimeLogCreate) SetNillableOperationName(v *string) *RuntimeLogCreate {
	if v != nil {
		_c.SetOperationName(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *RuntimeLogCreate) SetChannelID(v int) *RuntimeLogCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_c *RuntimeLogCreate) SetNillableChannelID(v *int) *RuntimeLogCreate {
	if v != nil {
		_c.SetChannelID(*v)
	}
	return _c
}

// SetChannelName sets the "channel_name" field.
func (_c *RuntimeLogCreate) SetChannelName(v string) *RuntimeLogCreate {
	_c.mutation.SetChannelName(v)
	return _c
}

// SetNillableChannelName sets the "channel_name" field if the given value is not nil.
func (_c *RuntimeLogCreate) SetNillableChannelName(v *string) *RuntimeLogCreate {
	if v != nil {
		_c.SetChannelName(*v)
	}
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *RuntimeLogCreate) SetModelID(v string) *RuntimeLogCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_c *RuntimeLogCreate) SetNillableModelID(v *string) *RuntimeLogCreate {
	if v != nil {
		_c.SetModelID(*v)
	}
	return _c
}

// SetFieldsJSON sets the "fields_json" field.
func (_c *RuntimeLogCreate) SetFieldsJSON(v map[string]interface{}) *RuntimeLogCreate {
	_c.mutation.SetFieldsJSON(v)
	return _c
}

// Mutation returns the RuntimeLogMutation object of the builder.
func (_c *RuntimeLogCreate) Mutation() *RuntimeLogMutation {
	return _c.mutation
}

// Save creates the RuntimeLog in the database.
func (_c *RuntimeLogCreate) Save(ctx context.Context) (*RuntimeLog, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RuntimeLogCreate) SaveX(ctx context.Context) *RuntimeLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuntimeLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuntimeLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RuntimeLogCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if runtimelog.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized runtimelog.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := runtimelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if runtimelog.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized runtimelog.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := runtimelog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Caller(); !ok {
		v := runtimelog.DefaultCaller
		_c.mutation.SetCaller(v)
	}
	if _, ok := _c.mutation.FieldsJSON(); !ok {
		v := runtimelog.DefaultFieldsJSON
		_c.mutation.SetFieldsJSON(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RuntimeLogCreate) check() error {
	if _, ok := _c.mutation.Logger(); !ok {
		return &ValidationError{Name: "logger", err: errors.New(`ent: missing required field "RuntimeLog.logger"`)}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "RuntimeLog.level"`)}
	}
	if v, ok := _c.mutation.Level(); ok {
		if err := runtimelog.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "RuntimeLog.level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "RuntimeLog.message"`)}
	}
	if _, ok := _c.mutation.FieldsJSON(); !ok {
		return &ValidationError{Name: "fields_json", err: errors.New(`ent: missing required field "RuntimeLog.fields_json"`)}
	}
	return nil
}

func (_c *RuntimeLogCreate) sqlSave(ctx context.Context) (*RuntimeLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RuntimeLogCreate) createSpec() (*RuntimeLog, *sqlgraph.CreateSpec) {
	var (
		_node = &RuntimeLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(runtimelog.Table, sqlgraph.NewFieldSpec(runtimelog.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(runtimelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(runtimelog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Logger(); ok {
		_spec.SetField(runtimelog.FieldLogger, field.TypeString, value)
		_node.Logger = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(runtimelog.FieldLevel, field.TypeEnum, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(runtimelog.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Caller(); ok {
		_spec.SetField(runtimelog.FieldCaller, field.TypeString, value)
		_node.Caller = value
	}
	if value, ok := _c.mutation.TraceID(); ok {
		_spec.SetField(runtimelog.FieldTraceID, field.TypeString, value)
		_node.TraceID = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(runtimelog.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.OperationName(); ok {
		_spec.SetField(runtimelog.FieldOperationName, field.TypeString, value)
		_node.OperationName = &value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(runtimelog.FieldChannelID, field.TypeInt, value)
		_node.ChannelID = &value
	}
	if value, ok := _c.mutation.ChannelName(); ok {
		_spec.SetField(runtimelog.FieldChannelName, field.TypeString, value)
		_node.ChannelName = &value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(runtimelog.FieldModelID, field.TypeString, value)
		_node.ModelID = &value
	}
	if value, ok := _c.mutation.FieldsJSON(); ok {
		_spec.SetField(runtimelog.FieldFieldsJSON, field.TypeJSON, value)
		_node.FieldsJSON = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RuntimeLog.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RuntimeLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RuntimeLogCreate) OnConflict(opts ...sql.ConflictOption) *RuntimeLogUpsertOne {
	_c.conflict = opts
	return &RuntimeLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RuntimeLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RuntimeLogCreate) OnConflictColumns(columns ...string) *RuntimeLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RuntimeLogUpsertOne{
		create: _c,
	}
}

type (
	// RuntimeLogUpsertOne is the builder for "upsert"-ing
	//  one RuntimeLog node.
	RuntimeLogUpsertOne struct {
		create *RuntimeLogCreate
	}

	// RuntimeLogUpsert is the "OnConflict" setter.
	RuntimeLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RuntimeLogUpsert) SetUpdatedAt(v time.Time) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateUpdatedAt() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldUpdatedAt)
	return u
}

// SetLogger sets the "logger" field.
func (u *RuntimeLogUpsert) SetLogger(v string) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldLogger, v)
	return u
}

// UpdateLogger sets the "logger" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateLogger() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldLogger)
	return u
}

// SetLevel sets the "level" field.
func (u *RuntimeLogUpsert) SetLevel(v runtimelog.Level) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldLevel, v)
	return u
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateLevel() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldLevel)
	return u
}

// SetMessage sets the "message" field.
func (u *RuntimeLogUpsert) SetMessage(v string) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateMessage() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldMessage)
	return u
}

// SetCaller sets the "caller" field.
func (u *RuntimeLogUpsert) SetCaller(v string) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldCaller, v)
	return u
}

// UpdateCaller sets the "caller" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateCaller() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldCaller)
	return u
}

// ClearCaller clears the value of the "caller" field.
func (u *RuntimeLogUpsert) ClearCaller() *RuntimeLogUpsert {
	u.SetNull(runtimelog.FieldCaller)
	return u
}

// SetTraceID sets the "trace_id" field.
func (u *RuntimeLogUpsert) SetTraceID(v string) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldTraceID, v)
	return u
}

// UpdateTraceID sets the "trace_id" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateTraceID() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldTraceID)
	return u
}

// ClearTraceID clears the value of the "trace_id" field.
func (u *RuntimeLogUpsert) ClearTraceID() *RuntimeLogUpsert {
	u.SetNull(runtimelog.FieldTraceID)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *RuntimeLogUpsert) SetRequestID(v string) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateRequestID() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RuntimeLogUpsert) ClearRequestID() *RuntimeLogUpsert {
	u.SetNull(runtimelog.FieldRequestID)
	return u
}

// SetOperationName sets the "operation_name" field.
func (u *RuntimeLogUpsert) SetOperationName(v string) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldOperationName, v)
	return u
}

// UpdateOperationName sets the "operation_name" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateOperationName() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldOperationName)
	return u
}

// ClearOperationName clears the value of the "operation_name" field.
func (u *RuntimeLogUpsert) ClearOperationName() *RuntimeLogUpsert {
	u.SetNull(runtimelog.FieldOperationName)
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *RuntimeLogUpsert) SetChannelID(v int) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateChannelID() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldChannelID)
	return u
}

// AddChannelID adds v to the "channel_id" field.
func (u *RuntimeLogUpsert) AddChannelID(v int) *RuntimeLogUpsert {
	u.Add(runtimelog.FieldChannelID, v)
	return u
}

// ClearChannelID clears the value of the "channel_id" field.
func (u *RuntimeLogUpsert) ClearChannelID() *RuntimeLogUpsert {
	u.SetNull(runtimelog.FieldChannelID)
	return u
}

// SetChannelName sets the "channel_name" field.
func (u *RuntimeLogUpsert) SetChannelName(v string) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldChannelName, v)
	return u
}

// UpdateChannelName sets the "channel_name" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateChannelName() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldChannelName)
	return u
}

// ClearChannelName clears the value of the "channel_name" field.
func (u *RuntimeLogUpsert) ClearChannelName() *RuntimeLogUpsert {
	u.SetNull(runtimelog.FieldChannelName)
	return u
}

// SetModelID sets the "model_id" field.
func (u *RuntimeLogUpsert) SetModelID(v string) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateModelID() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldModelID)
	return u
}

// ClearModelID clears the value of the "model_id" field.
func (u *RuntimeLogUpsert) ClearModelID() *RuntimeLogUpsert {
	u.SetNull(runtimelog.FieldModelID)
	return u
}

// SetFieldsJSON sets the "fields_json" field.
func (u *RuntimeLogUpsert) SetFieldsJSON(v map[string]interface{}) *RuntimeLogUpsert {
	u.Set(runtimelog.FieldFieldsJSON, v)
	return u
}

// UpdateFieldsJSON sets the "fields_json" field to the value that was provided on create.
func (u *RuntimeLogUpsert) UpdateFieldsJSON() *RuntimeLogUpsert {
	u.SetExcluded(runtimelog.FieldFieldsJSON)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RuntimeLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RuntimeLogUpsertOne) UpdateNewValues() *RuntimeLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(runtimelog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RuntimeLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RuntimeLogUpsertOne) Ignore() *RuntimeLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RuntimeLogUpsertOne) DoNothing() *RuntimeLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RuntimeLogCreate.OnConflict
// documentation for more info.
func (u *RuntimeLogUpsertOne) Update(set func(*RuntimeLogUpsert)) *RuntimeLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RuntimeLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RuntimeLogUpsertOne) SetUpdatedAt(v time.Time) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateUpdatedAt() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLogger sets the "logger" field.
func (u *RuntimeLogUpsertOne) SetLogger(v string) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetLogger(v)
	})
}

// UpdateLogger sets the "logger" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateLogger() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateLogger()
	})
}

// SetLevel sets the "level" field.
func (u *RuntimeLogUpsertOne) SetLevel(v runtimelog.Level) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateLevel() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateLevel()
	})
}

// SetMessage sets the "message" field.
func (u *RuntimeLogUpsertOne) SetMessage(v string) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateMessage() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateMessage()
	})
}

// SetCaller sets the "caller" field.
func (u *RuntimeLogUpsertOne) SetCaller(v string) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetCaller(v)
	})
}

// UpdateCaller sets the "caller" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateCaller() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateCaller()
	})
}

// ClearCaller clears the value of the "caller" field.
func (u *RuntimeLogUpsertOne) ClearCaller() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearCaller()
	})
}

// SetTraceID sets the "trace_id" field.
func (u *RuntimeLogUpsertOne) SetTraceID(v string) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetTraceID(v)
	})
}

// UpdateTraceID sets the "trace_id" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateTraceID() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateTraceID()
	})
}

// ClearTraceID clears the value of the "trace_id" field.
func (u *RuntimeLogUpsertOne) ClearTraceID() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearTraceID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *RuntimeLogUpsertOne) SetRequestID(v string) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateRequestID() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RuntimeLogUpsertOne) ClearRequestID() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearRequestID()
	})
}

// SetOperationName sets the "operation_name" field.
func (u *RuntimeLogUpsertOne) SetOperationName(v string) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetOperationName(v)
	})
}

// UpdateOperationName sets the "operation_name" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateOperationName() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateOperationName()
	})
}

// ClearOperationName clears the value of the "operation_name" field.
func (u *RuntimeLogUpsertOne) ClearOperationName() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearOperationName()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *RuntimeLogUpsertOne) SetChannelID(v int) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *RuntimeLogUpsertOne) AddChannelID(v int) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateChannelID() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateChannelID()
	})
}

// ClearChannelID clears the value of the "channel_id" field.
func (u *RuntimeLogUpsertOne) ClearChannelID() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearChannelID()
	})
}

// SetChannelName sets the "channel_name" field.
func (u *RuntimeLogUpsertOne) SetChannelName(v string) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetChannelName(v)
	})
}

// UpdateChannelName sets the "channel_name" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateChannelName() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateChannelName()
	})
}

// ClearChannelName clears the value of the "channel_name" field.
func (u *RuntimeLogUpsertOne) ClearChannelName() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearChannelName()
	})
}

// SetModelID sets the "model_id" field.
func (u *RuntimeLogUpsertOne) SetModelID(v string) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateModelID() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateModelID()
	})
}

// ClearModelID clears the value of the "model_id" field.
func (u *RuntimeLogUpsertOne) ClearModelID() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearModelID()
	})
}

// SetFieldsJSON sets the "fields_json" field.
func (u *RuntimeLogUpsertOne) SetFieldsJSON(v map[string]interface{}) *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetFieldsJSON(v)
	})
}

// UpdateFieldsJSON sets the "fields_json" field to the value that was provided on create.
func (u *RuntimeLogUpsertOne) UpdateFieldsJSON() *RuntimeLogUpsertOne {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateFieldsJSON()
	})
}

// Exec executes the query.
func (u *RuntimeLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RuntimeLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RuntimeLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RuntimeLogUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RuntimeLogUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RuntimeLogCreateBulk is the builder for creating many RuntimeLog entities in bulk.
type RuntimeLogCreateBulk struct {
	config
	err      error
	builders []*RuntimeLogCreate
	conflict []sql.ConflictOption
}

// Save creates the RuntimeLog entities in the database.
func (_c *RuntimeLogCreateBulk) Save(ctx context.Context) ([]*RuntimeLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RuntimeLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RuntimeLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RuntimeLogCreateBulk) SaveX(ctx context.Context) []*RuntimeLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuntimeLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuntimeLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RuntimeLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RuntimeLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RuntimeLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *RuntimeLogUpsertBulk {
	_c.conflict = opts
	return &RuntimeLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RuntimeLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RuntimeLogCreateBulk) OnConflictColumns(columns ...string) *RuntimeLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RuntimeLogUpsertBulk{
		create: _c,
	}
}

// RuntimeLogUpsertBulk is the builder for "upsert"-ing
// a bulk of RuntimeLog nodes.
type RuntimeLogUpsertBulk struct {
	create *RuntimeLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RuntimeLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RuntimeLogUpsertBulk) UpdateNewValues() *RuntimeLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(runtimelog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RuntimeLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RuntimeLogUpsertBulk) Ignore() *RuntimeLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RuntimeLogUpsertBulk) DoNothing() *RuntimeLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RuntimeLogCreateBulk.OnConflict
// documentation for more info.
func (u *RuntimeLogUpsertBulk) Update(set func(*RuntimeLogUpsert)) *RuntimeLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RuntimeLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RuntimeLogUpsertBulk) SetUpdatedAt(v time.Time) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateUpdatedAt() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLogger sets the "logger" field.
func (u *RuntimeLogUpsertBulk) SetLogger(v string) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetLogger(v)
	})
}

// UpdateLogger sets the "logger" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateLogger() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateLogger()
	})
}

// SetLevel sets the "level" field.
func (u *RuntimeLogUpsertBulk) SetLevel(v runtimelog.Level) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateLevel() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateLevel()
	})
}

// SetMessage sets the "message" field.
func (u *RuntimeLogUpsertBulk) SetMessage(v string) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateMessage() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateMessage()
	})
}

// SetCaller sets the "caller" field.
func (u *RuntimeLogUpsertBulk) SetCaller(v string) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetCaller(v)
	})
}

// UpdateCaller sets the "caller" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateCaller() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateCaller()
	})
}

// ClearCaller clears the value of the "caller" field.
func (u *RuntimeLogUpsertBulk) ClearCaller() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearCaller()
	})
}

// SetTraceID sets the "trace_id" field.
func (u *RuntimeLogUpsertBulk) SetTraceID(v string) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetTraceID(v)
	})
}

// UpdateTraceID sets the "trace_id" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateTraceID() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateTraceID()
	})
}

// ClearTraceID clears the value of the "trace_id" field.
func (u *RuntimeLogUpsertBulk) ClearTraceID() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearTraceID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *RuntimeLogUpsertBulk) SetRequestID(v string) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateRequestID() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RuntimeLogUpsertBulk) ClearRequestID() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearRequestID()
	})
}

// SetOperationName sets the "operation_name" field.
func (u *RuntimeLogUpsertBulk) SetOperationName(v string) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetOperationName(v)
	})
}

// UpdateOperationName sets the "operation_name" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateOperationName() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateOperationName()
	})
}

// ClearOperationName clears the value of the "operation_name" field.
func (u *RuntimeLogUpsertBulk) ClearOperationName() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearOperationName()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *RuntimeLogUpsertBulk) SetChannelID(v int) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *RuntimeLogUpsertBulk) AddChannelID(v int) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateChannelID() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateChannelID()
	})
}

// ClearChannelID clears the value of the "channel_id" field.
func (u *RuntimeLogUpsertBulk) ClearChannelID() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearChannelID()
	})
}

// SetChannelName sets the "channel_name" field.
func (u *RuntimeLogUpsertBulk) SetChannelName(v string) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetChannelName(v)
	})
}

// UpdateChannelName sets the "channel_name" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateChannelName() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateChannelName()
	})
}

// ClearChannelName clears the value of the "channel_name" field.
func (u *RuntimeLogUpsertBulk) ClearChannelName() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearChannelName()
	})
}

// SetModelID sets the "model_id" field.
func (u *RuntimeLogUpsertBulk) SetModelID(v string) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateModelID() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateModelID()
	})
}

// ClearModelID clears the value of the "model_id" field.
func (u *RuntimeLogUpsertBulk) ClearModelID() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.ClearModelID()
	})
}

// SetFieldsJSON sets the "fields_json" field.
func (u *RuntimeLogUpsertBulk) SetFieldsJSON(v map[string]interface{}) *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.SetFieldsJSON(v)
	})
}

// UpdateFieldsJSON sets the "fields_json" field to the value that was provided on create.
func (u *RuntimeLogUpsertBulk) UpdateFieldsJSON() *RuntimeLogUpsertBulk {
	return u.Update(func(s *RuntimeLogUpsert) {
		s.UpdateFieldsJSON()
	})
}

// Exec executes the query.
func (u *RuntimeLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RuntimeLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RuntimeLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RuntimeLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
