// Code generated by ent, DO NOT EDIT.

package modelprobeconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the modelprobeconfig type in the database.
	Label = "model_probe_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDisplayModel holds the string denoting the display_model field in the database.
	FieldDisplayModel = "display_model"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldActualModelID holds the string denoting the actual_model_id field in the database.
	FieldActualModelID = "actual_model_id"
	// FieldProbeEnabled holds the string denoting the probe_enabled field in the database.
	FieldProbeEnabled = "probe_enabled"
	// FieldConsecutiveFailures holds the string denoting the consecutive_failures field in the database.
	FieldConsecutiveFailures = "consecutive_failures"
	// FieldAutoDisabledAt holds the string denoting the auto_disabled_at field in the database.
	FieldAutoDisabledAt = "auto_disabled_at"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// Table holds the table name of the modelprobeconfig in the database.
	Table = "model_probe_configs"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "model_probe_configs"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
)

// Columns holds all SQL columns for modelprobeconfig fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDisplayModel,
	FieldChannelID,
	FieldActualModelID,
	FieldProbeEnabled,
	FieldConsecutiveFailures,
	FieldAutoDisabledAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultProbeEnabled holds the default value on creation for the "probe_enabled" field.
	DefaultProbeEnabled bool
	// DefaultConsecutiveFailures holds the default value on creation for the "consecutive_failures" field.
	DefaultConsecutiveFailures int
)

// OrderOption defines the ordering options for the ModelProbeConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDisplayModel orders the results by the display_model field.
func ByDisplayModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayModel, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByActualModelID orders the results by the actual_model_id field.
func ByActualModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualModelID, opts...).ToFunc()
}

// ByProbeEnabled orders the results by the probe_enabled field.
func ByProbeEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeEnabled, opts...).ToFunc()
}

// ByConsecutiveFailures orders the results by the consecutive_failures field.
func ByConsecutiveFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveFailures, opts...).ToFunc()
}

// ByAutoDisabledAt orders the results by the auto_disabled_at field.
func ByAutoDisabledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoDisabledAt, opts...).ToFunc()
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}
