// Code generated by ent, DO NOT EDIT.

package modelprobeconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// DisplayModel applies equality check predicate on the "display_model" field. It's identical to DisplayModelEQ.
func DisplayModel(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldDisplayModel, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldChannelID, v))
}

// ActualModelID applies equality check predicate on the "actual_model_id" field. It's identical to ActualModelIDEQ.
func ActualModelID(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldActualModelID, v))
}

// ProbeEnabled applies equality check predicate on the "probe_enabled" field. It's identical to ProbeEnabledEQ.
func ProbeEnabled(v bool) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldProbeEnabled, v))
}

// ConsecutiveFailures applies equality check predicate on the "consecutive_failures" field. It's identical to ConsecutiveFailuresEQ.
func ConsecutiveFailures(v int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// AutoDisabledAt applies equality check predicate on the "auto_disabled_at" field. It's identical to AutoDisabledAtEQ.
func AutoDisabledAt(v int64) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldAutoDisabledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// DisplayModelEQ applies the EQ predicate on the "display_model" field.
func DisplayModelEQ(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldDisplayModel, v))
}

// DisplayModelNEQ applies the NEQ predicate on the "display_model" field.
func DisplayModelNEQ(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNEQ(FieldDisplayModel, v))
}

// DisplayModelIn applies the In predicate on the "display_model" field.
func DisplayModelIn(vs ...string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldIn(FieldDisplayModel, vs...))
}

// DisplayModelNotIn applies the NotIn predicate on the "display_model" field.
func DisplayModelNotIn(vs ...string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNotIn(FieldDisplayModel, vs...))
}

// DisplayModelGT applies the GT predicate on the "display_model" field.
func DisplayModelGT(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGT(FieldDisplayModel, v))
}

// DisplayModelGTE applies the GTE predicate on the "display_model" field.
func DisplayModelGTE(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGTE(FieldDisplayModel, v))
}

// DisplayModelLT applies the LT predicate on the "display_model" field.
func DisplayModelLT(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLT(FieldDisplayModel, v))
}

// DisplayModelLTE applies the LTE predicate on the "display_model" field.
func DisplayModelLTE(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLTE(FieldDisplayModel, v))
}

// DisplayModelContains applies the Contains predicate on the "display_model" field.
func DisplayModelContains(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldContains(FieldDisplayModel, v))
}

// DisplayModelHasPrefix applies the HasPrefix predicate on the "display_model" field.
func DisplayModelHasPrefix(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldHasPrefix(FieldDisplayModel, v))
}

// DisplayModelHasSuffix applies the HasSuffix predicate on the "display_model" field.
func DisplayModelHasSuffix(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldHasSuffix(FieldDisplayModel, v))
}

// DisplayModelEqualFold applies the EqualFold predicate on the "display_model" field.
func DisplayModelEqualFold(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEqualFold(FieldDisplayModel, v))
}

// DisplayModelContainsFold applies the ContainsFold predicate on the "display_model" field.
func DisplayModelContainsFold(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldContainsFold(FieldDisplayModel, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNotIn(FieldChannelID, vs...))
}

// ActualModelIDEQ applies the EQ predicate on the "actual_model_id" field.
func ActualModelIDEQ(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldActualModelID, v))
}

// ActualModelIDNEQ applies the NEQ predicate on the "actual_model_id" field.
func ActualModelIDNEQ(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNEQ(FieldActualModelID, v))
}

// ActualModelIDIn applies the In predicate on the "actual_model_id" field.
func ActualModelIDIn(vs ...string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldIn(FieldActualModelID, vs...))
}

// ActualModelIDNotIn applies the NotIn predicate on the "actual_model_id" field.
func ActualModelIDNotIn(vs ...string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNotIn(FieldActualModelID, vs...))
}

// ActualModelIDGT applies the GT predicate on the "actual_model_id" field.
func ActualModelIDGT(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGT(FieldActualModelID, v))
}

// ActualModelIDGTE applies the GTE predicate on the "actual_model_id" field.
func ActualModelIDGTE(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGTE(FieldActualModelID, v))
}

// ActualModelIDLT applies the LT predicate on the "actual_model_id" field.
func ActualModelIDLT(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLT(FieldActualModelID, v))
}

// ActualModelIDLTE applies the LTE predicate on the "actual_model_id" field.
func ActualModelIDLTE(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLTE(FieldActualModelID, v))
}

// ActualModelIDContains applies the Contains predicate on the "actual_model_id" field.
func ActualModelIDContains(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldContains(FieldActualModelID, v))
}

// ActualModelIDHasPrefix applies the HasPrefix predicate on the "actual_model_id" field.
func ActualModelIDHasPrefix(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldHasPrefix(FieldActualModelID, v))
}

// ActualModelIDHasSuffix applies the HasSuffix predicate on the "actual_model_id" field.
func ActualModelIDHasSuffix(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldHasSuffix(FieldActualModelID, v))
}

// ActualModelIDEqualFold applies the EqualFold predicate on the "actual_model_id" field.
func ActualModelIDEqualFold(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEqualFold(FieldActualModelID, v))
}

// ActualModelIDContainsFold applies the ContainsFold predicate on the "actual_model_id" field.
func ActualModelIDContainsFold(v string) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldContainsFold(FieldActualModelID, v))
}

// ProbeEnabledEQ applies the EQ predicate on the "probe_enabled" field.
func ProbeEnabledEQ(v bool) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldProbeEnabled, v))
}

// ProbeEnabledNEQ applies the NEQ predicate on the "probe_enabled" field.
func ProbeEnabledNEQ(v bool) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNEQ(FieldProbeEnabled, v))
}

// ConsecutiveFailuresEQ applies the EQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresEQ(v int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresNEQ applies the NEQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNEQ(v int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresIn applies the In predicate on the "consecutive_failures" field.
func ConsecutiveFailuresIn(vs ...int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresNotIn applies the NotIn predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNotIn(vs ...int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNotIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresGT applies the GT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGT(v int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresGTE applies the GTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGTE(v int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGTE(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLT applies the LT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLT(v int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLTE applies the LTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLTE(v int) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLTE(FieldConsecutiveFailures, v))
}

// AutoDisabledAtEQ applies the EQ predicate on the "auto_disabled_at" field.
func AutoDisabledAtEQ(v int64) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldEQ(FieldAutoDisabledAt, v))
}

// AutoDisabledAtNEQ applies the NEQ predicate on the "auto_disabled_at" field.
func AutoDisabledAtNEQ(v int64) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNEQ(FieldAutoDisabledAt, v))
}

// AutoDisabledAtIn applies the In predicate on the "auto_disabled_at" field.
func AutoDisabledAtIn(vs ...int64) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldIn(FieldAutoDisabledAt, vs...))
}

// AutoDisabledAtNotIn applies the NotIn predicate on the "auto_disabled_at" field.
func AutoDisabledAtNotIn(vs ...int64) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNotIn(FieldAutoDisabledAt, vs...))
}

// AutoDisabledAtGT applies the GT predicate on the "auto_disabled_at" field.
func AutoDisabledAtGT(v int64) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGT(FieldAutoDisabledAt, v))
}

// AutoDisabledAtGTE applies the GTE predicate on the "auto_disabled_at" field.
func AutoDisabledAtGTE(v int64) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldGTE(FieldAutoDisabledAt, v))
}

// AutoDisabledAtLT applies the LT predicate on the "auto_disabled_at" field.
func AutoDisabledAtLT(v int64) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLT(FieldAutoDisabledAt, v))
}

// AutoDisabledAtLTE applies the LTE predicate on the "auto_disabled_at" field.
func AutoDisabledAtLTE(v int64) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldLTE(FieldAutoDisabledAt, v))
}

// AutoDisabledAtIsNil applies the IsNil predicate on the "auto_disabled_at" field.
func AutoDisabledAtIsNil() predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldIsNull(FieldAutoDisabledAt))
}

// AutoDisabledAtNotNil applies the NotNil predicate on the "auto_disabled_at" field.
func AutoDisabledAtNotNil() predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.FieldNotNull(FieldAutoDisabledAt))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelProbeConfig) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelProbeConfig) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelProbeConfig) predicate.ModelProbeConfig {
	return predicate.ModelProbeConfig(sql.NotPredicates(p))
}
