package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/authz"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/scopes"
)

// SetModelProbeEnabled is the resolver for the setModelProbeEnabled field.
func (r *mutationResolver) SetModelProbeEnabled(ctx context.Context, input SetModelProbeEnabledInput) (*ent.ModelProbeConfig, error) {
	channelID, err := objects.ConvertGUIDToInt(input.ChannelID)
	if err != nil {
		return nil, fmt.Errorf("invalid channel id: %w", err)
	}

	return authz.RunWithScopeDecision(ctx, scopes.ScopeWriteChannels, func(ctx context.Context) (*ent.ModelProbeConfig, error) {
		return r.channelProbeService.ModelProbeConfigService.SetProbeEnabled(ctx, input.DisplayModel, channelID, input.ActualModelID, input.Enabled)
	})
}

// BatchSetChannelProbeEnabled is the resolver for the batchSetChannelProbeEnabled field.
func (r *mutationResolver) BatchSetChannelProbeEnabled(ctx context.Context, input BatchSetChannelProbeEnabledInput) ([]*ent.ModelProbeConfig, error) {
	channelID, err := objects.ConvertGUIDToInt(input.ChannelID)
	if err != nil {
		return nil, fmt.Errorf("invalid channel id: %w", err)
	}

	return authz.RunWithScopeDecision(ctx, scopes.ScopeWriteChannels, func(ctx context.Context) ([]*ent.ModelProbeConfig, error) {
		return r.channelProbeService.ModelProbeConfigService.BatchSetChannelProbeEnabled(ctx, input.DisplayModel, channelID, input.Enabled)
	})
}

// ModelProbeConfigs is the resolver for the modelProbeConfigs field.
func (r *queryResolver) ModelProbeConfigs(ctx context.Context, input GetModelProbeConfigsInput) ([]*ent.ModelProbeConfig, error) {
	return authz.RunWithScopeDecision(ctx, scopes.ScopeReadChannels, func(ctx context.Context) ([]*ent.ModelProbeConfig, error) {
		return r.channelProbeService.ModelProbeConfigService.GetByDisplayModels(ctx, input.DisplayModels)
	})
}
