package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/ent"
)

// ManualModelProbe is the resolver for the manualModelProbe field.
func (r *mutationResolver) ManualModelProbe(ctx context.Context, input ManualModelProbeInput) (bool, error) {
	panic(fmt.Errorf("not implemented: ManualModelProbe - manualModelProbe"))
}

// ModelHealthSnapshots is the resolver for the modelHealthSnapshots field.
func (r *queryResolver) ModelHealthSnapshots(ctx context.Context, input GetModelHealthSnapshotsInput) ([]*ent.ModelHealthSnapshot, error) {
	panic(fmt.Errorf("not implemented: ModelHealthSnapshots - modelHealthSnapshots"))
}

// ModelHealthHistory is the resolver for the modelHealthHistory field.
func (r *queryResolver) ModelHealthHistory(ctx context.Context, input GetModelHealthHistoryInput) ([]*ent.ModelHealthHistory, error) {
	panic(fmt.Errorf("not implemented: ModelHealthHistory - modelHealthHistory"))
}
