package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
	"time"

	"github.com/looplj/axonhub/internal/authz"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/modelhealthhistory"
	"github.com/looplj/axonhub/internal/ent/modelhealthsnapshot"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/scopes"
	"github.com/looplj/axonhub/internal/server/biz"
	"github.com/samber/lo"
)

// ManualModelProbe is the resolver for the manualModelProbe field.
func (r *mutationResolver) ManualModelProbe(ctx context.Context, input ManualModelProbeInput) (bool, error) {
	channelID, err := objects.ConvertGUIDToInt(input.ChannelID)
	if err != nil {
		return false, fmt.Errorf("invalid channel id: %w", err)
	}

	target := biz.ModelHealthProbeTarget{
		DisplayModel:  input.DisplayModel,
		ActualModelID: input.ActualModelID,
		ChannelID:     channelID,
	}

	_, err = authz.RunWithScopeDecision(ctx, scopes.ScopeWriteChannels, func(ctx context.Context) (bool, error) {
		return true, r.channelProbeService.RunManualModelProbe(ctx, target, time.Now().UTC())
	})
	if err != nil {
		return false, err
	}

	return true, nil
}

// ResetDiscoveredModelHealth is the resolver for the resetDiscoveredModelHealth field.
func (r *mutationResolver) ResetDiscoveredModelHealth(ctx context.Context) (bool, error) {
	_, err := authz.RunWithScopeDecision(ctx, scopes.ScopeWriteChannels, func(ctx context.Context) (bool, error) {
		_, err := r.client.ModelHealthHistory.Delete().
			Where(modelhealthhistory.SourceEQ(biz.ModelHealthSourceDiscoveredRecentUsage)).
			Exec(ctx)
		if err != nil {
			return false, err
		}

		_, err = r.client.ModelHealthSnapshot.Delete().
			Where(modelhealthsnapshot.SourceEQ(biz.ModelHealthSourceDiscoveredRecentUsage)).
			Exec(ctx)
		if err != nil {
			return false, err
		}

		return true, nil
	})
	if err != nil {
		return false, err
	}

	return true, nil
}

// ModelHealthSnapshots is the resolver for the modelHealthSnapshots field.
func (r *queryResolver) ModelHealthSnapshots(ctx context.Context, input GetModelHealthSnapshotsInput) ([]*ent.ModelHealthSnapshot, error) {
	return authz.RunWithScopeDecision(ctx, scopes.ScopeReadChannels, func(ctx context.Context) ([]*ent.ModelHealthSnapshot, error) {
		query := r.client.ModelHealthSnapshot.Query().Order(
			ent.Asc(modelhealthsnapshot.FieldDisplayModel),
			ent.Asc(modelhealthsnapshot.FieldActualModelID),
			ent.Asc(modelhealthsnapshot.FieldChannelID),
		).Where(modelhealthsnapshot.SourceEQ(biz.ModelHealthSourceAssociated))

		if len(input.DisplayModels) > 0 {
			query = query.Where(modelhealthsnapshot.DisplayModelIn(input.DisplayModels...))
		}

		snapshots, err := query.All(ctx)
		if err != nil {
			return nil, err
		}

		return buildModelHealthSnapshotRows(ctx, r.client, snapshots)
	})
}

// DiscoveredModelHealthSnapshots is the resolver for the discoveredModelHealthSnapshots field.
func (r *queryResolver) DiscoveredModelHealthSnapshots(ctx context.Context, input GetDiscoveredModelHealthSnapshotsInput) ([]*ent.ModelHealthSnapshot, error) {
	return authz.RunWithScopeDecision(ctx, scopes.ScopeReadChannels, func(ctx context.Context) ([]*ent.ModelHealthSnapshot, error) {
		expireBefore := time.Now().UTC().Unix() - biz.ModelHealthDiscoveredRetentionForResolver()

		query := r.client.ModelHealthSnapshot.Query().Order(
			ent.Asc(modelhealthsnapshot.FieldDisplayModel),
			ent.Asc(modelhealthsnapshot.FieldActualModelID),
			ent.Asc(modelhealthsnapshot.FieldChannelID),
		).Where(
			modelhealthsnapshot.SourceEQ(biz.ModelHealthSourceDiscoveredRecentUsage),
			modelhealthsnapshot.ProbedAtGTE(expireBefore),
		)

		if len(input.DisplayModels) > 0 {
			query = query.Where(modelhealthsnapshot.DisplayModelIn(input.DisplayModels...))
		}

		snapshots, err := query.All(ctx)
		if err != nil {
			return nil, err
		}

		probeEnabledAssociatedActualModels, err := listProbeEnabledAssociatedActualModels(ctx, r.client)
		if err != nil {
			return nil, err
		}

		probeEnabledDisplayModels, err := listProbeEnabledDisplayModels(ctx, r.client)
		if err != nil {
			return nil, err
		}

		snapshots = filterDiscoveredSnapshots(snapshots, probeEnabledAssociatedActualModels, probeEnabledDisplayModels)

		return buildModelHealthSnapshotRows(ctx, r.client, snapshots)
	})
}

// ModelHealthHistory is the resolver for the modelHealthHistory field.
func (r *queryResolver) ModelHealthHistory(ctx context.Context, input GetModelHealthHistoryInput) ([]*ent.ModelHealthHistory, error) {
	return authz.RunWithScopeDecision(ctx, scopes.ScopeReadChannels, func(ctx context.Context) ([]*ent.ModelHealthHistory, error) {
		query := r.client.ModelHealthHistory.Query().Order(ent.Desc(modelhealthhistory.FieldProbedAt))

		predicates := make([]predicate.ModelHealthHistory, 0, 3)
		if input.DisplayModel != nil && *input.DisplayModel != "" {
			predicates = append(predicates, modelhealthhistory.DisplayModelEQ(*input.DisplayModel))
		}
		if input.ActualModelID != nil && *input.ActualModelID != "" {
			predicates = append(predicates, modelhealthhistory.ActualModelIDEQ(*input.ActualModelID))
		}
		if len(input.ChannelIDs) > 0 {
			channelIDs := lo.Map(input.ChannelIDs, func(item *objects.GUID, _ int) int {
				return item.ID
			})
			predicates = append(predicates, modelhealthhistory.ChannelIDIn(channelIDs...))
		}
		if len(predicates) > 0 {
			query = query.Where(predicates...)
		}

		return query.All(ctx)
	})
}
