# Copy from https://github.com/spf13/cobra
# https://github.com/spf13/cobra/blob/master/LICENSE.txt
name: Test
on:
  push:
    branches:
      - "unstable"
      - "release/**"
  pull_request:
    branches:
      - "unstable"
      - "release/**"
env:
  GO111MODULE: on
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Test
        run: make test-backend-all
